In [1]:
import pandas as pd
import numpy as np

In [10]:
weather_data = {
    "day" : ["1/1/2017","1/2/2017","1/3/2017","1/4/2017"]*3,
    "city" : ["Mysore"]*4 + ["Delhi"]*4 + ["Mumbai"]*4,
    "temperature" : [32,None,28,None,32,None,None,34,40,None,None,25],
    "windspeed" : [6,7,None,7,None,None,None,8,None,None,8,8],
    "event" : ["Rain",None]*2 + [None]*2 + ["Snow"]*2+["Rain","Sunny"]*2
}

df = pd.DataFrame(weather_data)
df

         day    city  temperature  windspeed  event
0   1/1/2017  Mysore         32.0        6.0   Rain
1   1/2/2017  Mysore          NaN        7.0   None
2   1/3/2017  Mysore         28.0        NaN   Rain
3   1/4/2017  Mysore          NaN        7.0   None
4   1/1/2017   Delhi         32.0        NaN   None
5   1/2/2017   Delhi          NaN        NaN   None
6   1/3/2017   Delhi          NaN        NaN   Snow
7   1/4/2017   Delhi         34.0        8.0   Snow
8   1/1/2017  Mumbai         40.0        NaN   Rain
9   1/2/2017  Mumbai          NaN        NaN  Sunny
10  1/3/2017  Mumbai          NaN        8.0   Rain
11  1/4/2017  Mumbai         25.0        8.0  Sunny

In [11]:
df1=df.dropna()
df1

         day    city  temperature  windspeed  event
0   1/1/2017  Mysore         32.0        6.0   Rain
7   1/4/2017   Delhi         34.0        8.0   Snow
11  1/4/2017  Mumbai         25.0        8.0  Sunny

In [12]:
#fill a  specific value on all columns
df2 = df.fillna('######')
df2

         day    city temperature windspeed   event
0   1/1/2017  Mysore        32.0       6.0    Rain
1   1/2/2017  Mysore      ######       7.0  ######
2   1/3/2017  Mysore        28.0    ######    Rain
3   1/4/2017  Mysore      ######       7.0  ######
4   1/1/2017   Delhi        32.0    ######  ######
5   1/2/2017   Delhi      ######    ######  ######
6   1/3/2017   Delhi      ######    ######    Snow
7   1/4/2017   Delhi        34.0       8.0    Snow
8   1/1/2017  Mumbai        40.0    ######    Rain
9   1/2/2017  Mumbai      ######    ######   Sunny
10  1/3/2017  Mumbai      ######       8.0    Rain
11  1/4/2017  Mumbai        25.0       8.0   Sunny

In [13]:
#Fill Column Specific Values:
df3 = df.fillna({'temperature':25,'windspeed':'6.5','event':"No Event"})
df3

         day    city  temperature windspeed     event
0   1/1/2017  Mysore         32.0       6.0      Rain
1   1/2/2017  Mysore         25.0       7.0  No Event
2   1/3/2017  Mysore         28.0       6.5      Rain
3   1/4/2017  Mysore         25.0       7.0  No Event
4   1/1/2017   Delhi         32.0       6.5  No Event
5   1/2/2017   Delhi         25.0       6.5  No Event
6   1/3/2017   Delhi         25.0       6.5      Snow
7   1/4/2017   Delhi         34.0       8.0      Snow
8   1/1/2017  Mumbai         40.0       6.5      Rain
9   1/2/2017  Mumbai         25.0       6.5     Sunny
10  1/3/2017  Mumbai         25.0       8.0      Rain
11  1/4/2017  Mumbai         25.0       8.0     Sunny

In [14]:
# forward fill
df4=df.ffill()
df4

         day    city  temperature  windspeed  event
0   1/1/2017  Mysore         32.0        6.0   Rain
1   1/2/2017  Mysore         32.0        7.0   Rain
2   1/3/2017  Mysore         28.0        7.0   Rain
3   1/4/2017  Mysore         28.0        7.0   Rain
4   1/1/2017   Delhi         32.0        7.0   Rain
5   1/2/2017   Delhi         32.0        7.0   Rain
6   1/3/2017   Delhi         32.0        7.0   Snow
7   1/4/2017   Delhi         34.0        8.0   Snow
8   1/1/2017  Mumbai         40.0        8.0   Rain
9   1/2/2017  Mumbai         40.0        8.0  Sunny
10  1/3/2017  Mumbai         40.0        8.0   Rain
11  1/4/2017  Mumbai         25.0        8.0  Sunny

In [16]:
#backward fill
df5 = df.bfill()
df5

         day    city  temperature  windspeed  event
0   1/1/2017  Mysore         32.0        6.0   Rain
1   1/2/2017  Mysore         28.0        7.0   Rain
2   1/3/2017  Mysore         28.0        7.0   Rain
3   1/4/2017  Mysore         32.0        7.0   Snow
4   1/1/2017   Delhi         32.0        8.0   Snow
5   1/2/2017   Delhi         34.0        8.0   Snow
6   1/3/2017   Delhi         34.0        8.0   Snow
7   1/4/2017   Delhi         34.0        8.0   Snow
8   1/1/2017  Mumbai         40.0        8.0   Rain
9   1/2/2017  Mumbai         25.0        8.0  Sunny
10  1/3/2017  Mumbai         25.0        8.0   Rain
11  1/4/2017  Mumbai         25.0        8.0  Sunny