In [1]:
import pandas as pd

In [3]:
#Create Data Without a File

data = {
    "Name": ["Bob", "Martin", "Rahul"],
    "Age": [30, 28, 25],
    "City": ["Chennai", "Chennai", "Bangalore"]
}

df = pd.DataFrame(data)

df

     Name  Age       City
0     Bob   30    Chennai
1  Martin   28    Chennai
2   Rahul   25  Bangalore

In [4]:
#Understanding DataFrame
type(df)

pandas.core.frame.DataFrame

In [14]:
df = pd.read_csv("/Users/mukundanramesh/projects/ai_ml_course_bootcamp_practice/ai-ml-course-bootcamp/Pandas/Pandas Mastery/Datasets/employees.csv")
df.head()

         EmployeeID   Name
1 Bob            QA  70000
2 Martin         HR  65000
3 Rahul   Developer  90000
4 Priya          QA  75000
5 Arun    Developer  95000

In [15]:
df.tail()

         EmployeeID   Name
1 Bob            QA  70000
2 Martin         HR  65000
3 Rahul   Developer  90000
4 Priya          QA  75000
5 Arun    Developer  95000

In [17]:
#Dataset Dimensions
df.shape

(5, 2)

In [18]:
#Column Names
df.columns

Index(['EmployeeID', 'Name'], dtype='object')

In [19]:
list(df.columns)

['EmployeeID', 'Name']