In [1]:
import sqlite3, pandas as pd
con = sqlite3.connect("practice.db")
con.executescript(open("practice_setup.sql").read())

In [2]:
def run(q):
    return pd.read_sql(q, con)

In [3]:
"""-- 1. Basic filter + sort  [Service / screening]
-- Names and salaries of employees earning more than 65000,
-- highest salary first."""
query1 = 'Select name,salary from employees where salary > 65000 order by salary desc'
run(query1)

     name  salary
0   Arjun   95000
1   Sneha   88000
2   Divya   81000
3   Kavya   76000
4   Priya   72000
5  Ramesh   70000
6   Karan   68000

In [4]:
"""-- 2. INNER JOIN  [Service / screening]
-- Each employee's name alongside their dept_name.
-- (Think: who disappears here and why?)"""
query2 = 'Select e.name,d.dept_name from employees e INNER JOIN departments d on d.dept_id=e.dept_id'
run(query2)
# Nisha will disappear as her dept_id in not in the departments table

       name    dept_name
0     Arjun  Engineering
1     Priya  Engineering
2     Karan  Engineering
3     Divya  Engineering
4     Rohit        Sales
5     Sneha        Sales
6    Vikram        Sales
7     Anita           HR
8     Manoj           HR
9     Kavya      Finance
10   Suresh      Finance
11    Deepa    Marketing
12   Ramesh  Engineering
13  Lakshmi        Sales

In [5]:
"""-- 3. LEFT JOIN  [Service / joins]
-- Every employee's name with their dept_name,
-- INCLUDING anyone whose department is missing. 15 rows expected."""
query3 = 'Select e.name,d.dept_name from employees e LEFT JOIN departments d on d.dept_id=e.dept_id'
run(query3)

       name    dept_name
0     Arjun  Engineering
1     Priya  Engineering
2     Karan  Engineering
3     Divya  Engineering
4     Rohit        Sales
5     Sneha        Sales
6    Vikram        Sales
7     Anita           HR
8     Manoj           HR
9     Kavya      Finance
10   Suresh      Finance
11    Deepa    Marketing
12    Nisha         None
13   Ramesh  Engineering
14  Lakshmi        Sales