In [2]:
# 1. Count Letters Only  [Service / screening]
# Count how many alphabetic characters are in a string, ignoring digits and spaces.
# Example: "abc 123 xy" -> 5
s = "code42 is fun99"
print(sum([1 for i in s if i.isalpha()]))

9

In [4]:
# 2. Swap Case  [Service / string]
# Flip each letter's case: upper becomes lower and vice versa. No .swapcase().
# Example: "Hello World" -> "hELLO wORLD"
text = "Python Is Fun"
"".join(i.lower() if i.isupper() else i.upper() for i in text)

'pYTHON iS fUN'

In [6]:
# 3. Sum of Squares  [Service / logic]
# Return the sum of squares of numbers 1 to n.
# Example: n = 3 -> 14  (1 + 4 + 9)
n = 3
print(sum([i**2 for i in range(1,n+1)]))

14

In [9]:
# 4. Find First Repeated Element  [AI screen / logic]
# Return the first value that appears more than once as you scan left to right.
# Example: [1, 2, 3, 2, 1] -> 2
nums = [5, 3, 8, 3, 9, 5]
seen = set()
for num in nums:
    if num in seen:
        print(num)
        break
    seen.add(num)

3

In [14]:
# 5. Merge Two Lists Alternately  [Service / logic]
# Interleave two lists element by element.
# Example: [1, 2, 3], ['a', 'b', 'c'] -> [1, 'a', 2, 'b', 3, 'c']
a = [1, 2, 3]
b = ['a', 'b', 'c']
[item for pair in zip(a,b) for item in pair]

[1, 'a', 2, 'b', 3, 'c']

In [18]:
# 6. Diagonal Sum  [AI screen / numpy]
# Return the sum of the main diagonal of a square matrix.
# Example: [[1,2],[3,4]] -> 5  (1 + 4)
import numpy as np
matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
np_trace = np.trace(matrix)
print(np_trace)
print(matrix.diagonal().sum())

15
15

In [19]:
# 7. Count Values Above Threshold  [AI screen / data handling]
# Count how many elements are strictly greater than 50.
import numpy as np
arr = np.array([30, 60, 45, 80, 20, 90, 55])
len(arr[arr>50])

4

In [23]:
# 8. Normalize to Sum 1  [AI screen / data handling]
# Scale the array so all values add up to 1 (turn into probabilities).
import numpy as np
weights = np.array([2, 3, 5])
weights_scaled = weights/weights.sum()
weights_scaled.sum()

np.float64(1.0)

In [24]:
# 9. Replace Values Above Mean  [AI screen / data handling]
# Replace every value above the mean with 0, keep the rest.
import numpy as np
data = np.array([10, 50, 30, 80, 20, 70])
data[data>data.mean()]= 0
data

array([10,  0, 30,  0, 20,  0])

In [7]:
data = np.array([10, 50, 30, 80, 20, 70])
np.where(data > data.mean(), 0, data)

array([10,  0, 30,  0, 20,  0])

In [6]:
# 10. Row With Highest Sum  [AI screen / numpy]
# Return the index of the row whose values sum to the most.
# Example: [[1,2],[9,9]] -> 1
import numpy as np
grid = np.array([[1, 2, 3], [10, 10, 10], [4, 5, 6]])
print(np.sum(grid,axis=1))
np.sum(grid,axis=1).argmax()

[ 6 30 15]

np.int64(1)

In [33]:
# 11. Filter and Count  [AI screen / pandas]
# Count how many employees earn more than 50000.
import pandas as pd
emp = pd.DataFrame({
    "name": ["A", "B", "C", "D", "E"],
    "salary": [45000, 60000, 52000, 48000, 75000],
})
(emp['salary']>50000).sum()

np.int64(3)

In [36]:
# 12. Fill Missing With Group Mean  [AI screen / pandas]
# Fill missing scores with the mean score of that student's class.
import pandas as pd
import numpy as np
df = pd.DataFrame({
    "class": ["X", "X", "Y", "Y", "X", "Y"],
    "score": [80, np.nan, 70, 90, 60, np.nan],
})
df['score']=df['score'].fillna(df.groupby('class')['score'].transform('mean'))
df

  class  score
0     X   80.0
1     X   70.0
2     Y   70.0
3     Y   90.0
4     X   60.0
5     Y   80.0

In [1]:
# 13. Count by Category  [Service / pandas basics]
# Return how many products fall in each category.
import pandas as pd
products = pd.DataFrame({
    "product": ["P1", "P2", "P3", "P4", "P5"],
    "category": ["Food", "Tech", "Food", "Food", "Tech"],
})
products['category'].value_counts()

category
Food    3
Tech    2
Name: count, dtype: int64

In [3]:
# 14. Add a Flag Column  [AI screen / feature engineering]
# Add "is_adult": True if age >= 18, else False.
import pandas as pd
people = pd.DataFrame({
    "name": ["A", "B", "C", "D"],
    "age": [15, 22, 17, 30],
})

people['flag'] = people['age'].map(lambda x : True if x>=18 else False)
people['flag2'] = people['age'].map(lambda x : x>=18)
people

  name  age   flag  flag2
0    A   15  False  False
1    B   22   True   True
2    C   17  False  False
3    D   30   True   True

In [4]:
# 15. Average Per Group  [AI screen / groupby]
# Return the average salary per department.
import pandas as pd
staff = pd.DataFrame({
    "dept": ["IT", "HR", "IT", "HR", "IT"],
    "salary": [50000, 45000, 70000, 48000, 60000],
})
staff.groupby('dept').mean()

       salary
dept
HR    46500.0
IT    60000.0

In [9]:
# 1. Group Consecutive Numbers  [AI screen / logic]
# Split a sorted list into groups of consecutive runs.
# Example: [1, 2, 3, 5, 6, 8] -> [[1, 2, 3], [5, 6], [8]]
nums = [1, 2, 3, 5, 6, 8, 9, 10]
result = []
current_group = [nums[0]]
    
for i in range(1, len(nums)):
    if nums[i] == nums[i - 1] + 1:
        current_group.append(nums[i])
    else:
        result.append(current_group)
        current_group = [nums[i]]
        
result.append(current_group)
print(result)

[[1, 2, 3], [5, 6], [8, 9, 10]]

In [17]:
# 2. Count Word Frequency and Return Top 2  [AI screen / text]
# Return the two most frequent words with their counts.
# Example: "a b a c a b" -> [('a', 3), ('b', 2)]
from collections import Counter 
text = "the sun the moon the sun the star"
counts = Counter(text.lower().split())
sorted_dict = dict(sorted(counts.items(),key=lambda x : x[1],reverse=True))
[(k,sorted_dict[k]) for k in list(sorted_dict)[:2]]

[('the', 4), ('sun', 2)]

In [27]:
# 3. Check Balanced Brackets  [Service / logic]
# Return True if every opening bracket has a matching closing one, in order.
# Example: "(a[b]c)" -> True, "(a[b)c]" -> False
expr = "(a[b]{c})"
dict_brack = {")":"(","}":"{","]":"["}
stack = []

def brackets(expr):
    for char in expr:
        if char in dict_brack.values():
            stack.append(char)
        elif char in dict_brack:

            if not stack or stack.pop() != dict_brack[char]:
                return False
    return len(stack)==0

print(brackets(expr))
print(brackets(']a]'))

True
False

In [20]:
# 4. Flatten a Nested List (any depth)  [AI screen / logic]
# Flatten a list that may contain lists inside lists, to any depth.
# Example: [1, [2, [3, 4], 5], 6] -> [1, 2, 3, 4, 5, 6]
data = [1, [2, [3, 4], 5], [6, [7, [8]]]]
def flatten_list(nested_list):
    result = []
    for item in nested_list:
        # Check if the item is a list or tuple
        if isinstance(item, list):
            result.extend(flatten_list(item))
        else:
            result.append(item)
    return result
flatten_list(data)

[1, 2, 3, 4, 5, 6, 7, 8]

In [23]:
# 5. Find the Missing and Duplicate  [AI screen / logic]
# A list should hold 1 to n once each. One number is missing, one is duplicated.
# Return (duplicate, missing).
# Example: [1, 2, 2, 4], n=4 -> (2, 3)
arr = [1, 2, 3, 3, 5, 6]
n = 6
for i in range(1,n+1):
    if arr[i-1] != i:
        print((arr[i-1],i))

(3, 4)

In [28]:
# 1. Count Even Numbers  [Service / screening]
# Count how many even numbers are in a list.
# Example: [1, 2, 3, 4, 5, 6] -> 3
nums = [4, 7, 2, 9, 10, 15, 6]
sum([1 for i in nums if i%2==0])

4