In [2]:
# 1. Count Letters Only  [Service / screening]
# Count how many alphabetic characters are in a string, ignoring digits and spaces.
# Example: "abc 123 xy" -> 5
s = "code42 is fun99"
print(sum([1 for i in s if i.isalpha()]))

9

In [4]:
# 2. Swap Case  [Service / string]
# Flip each letter's case: upper becomes lower and vice versa. No .swapcase().
# Example: "Hello World" -> "hELLO wORLD"
text = "Python Is Fun"
"".join(i.lower() if i.isupper() else i.upper() for i in text)

'pYTHON iS fUN'

In [6]:
# 3. Sum of Squares  [Service / logic]
# Return the sum of squares of numbers 1 to n.
# Example: n = 3 -> 14  (1 + 4 + 9)
n = 3
print(sum([i**2 for i in range(1,n+1)]))

14

In [9]:
# 4. Find First Repeated Element  [AI screen / logic]
# Return the first value that appears more than once as you scan left to right.
# Example: [1, 2, 3, 2, 1] -> 2
nums = [5, 3, 8, 3, 9, 5]
seen = set()
for num in nums:
    if num in seen:
        print(num)
        break
    seen.add(num)

3

In [14]:
# 5. Merge Two Lists Alternately  [Service / logic]
# Interleave two lists element by element.
# Example: [1, 2, 3], ['a', 'b', 'c'] -> [1, 'a', 2, 'b', 3, 'c']
a = [1, 2, 3]
b = ['a', 'b', 'c']
[item for pair in zip(a,b) for item in pair]

[1, 'a', 2, 'b', 3, 'c']

In [18]:
# 6. Diagonal Sum  [AI screen / numpy]
# Return the sum of the main diagonal of a square matrix.
# Example: [[1,2],[3,4]] -> 5  (1 + 4)
import numpy as np
matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
np_trace = np.trace(matrix)
print(np_trace)
print(matrix.diagonal().sum())

15
15

In [19]:
# 7. Count Values Above Threshold  [AI screen / data handling]
# Count how many elements are strictly greater than 50.
import numpy as np
arr = np.array([30, 60, 45, 80, 20, 90, 55])
len(arr[arr>50])

4

In [23]:
# 8. Normalize to Sum 1  [AI screen / data handling]
# Scale the array so all values add up to 1 (turn into probabilities).
import numpy as np
weights = np.array([2, 3, 5])
weights_scaled = weights/weights.sum()
weights_scaled.sum()

np.float64(1.0)

In [24]:
# 9. Replace Values Above Mean  [AI screen / data handling]
# Replace every value above the mean with 0, keep the rest.
import numpy as np
data = np.array([10, 50, 30, 80, 20, 70])
data[data>data.mean()]= 0
data

array([10,  0, 30,  0, 20,  0])

In [7]:
data = np.array([10, 50, 30, 80, 20, 70])
np.where(data > data.mean(), 0, data)

array([10,  0, 30,  0, 20,  0])

In [6]:
# 10. Row With Highest Sum  [AI screen / numpy]
# Return the index of the row whose values sum to the most.
# Example: [[1,2],[9,9]] -> 1
import numpy as np
grid = np.array([[1, 2, 3], [10, 10, 10], [4, 5, 6]])
print(np.sum(grid,axis=1))
np.sum(grid,axis=1).argmax()

[ 6 30 15]

np.int64(1)

In [33]:
# 11. Filter and Count  [AI screen / pandas]
# Count how many employees earn more than 50000.
import pandas as pd
emp = pd.DataFrame({
    "name": ["A", "B", "C", "D", "E"],
    "salary": [45000, 60000, 52000, 48000, 75000],
})
(emp['salary']>50000).sum()

np.int64(3)

In [36]:
# 12. Fill Missing With Group Mean  [AI screen / pandas]
# Fill missing scores with the mean score of that student's class.
import pandas as pd
import numpy as np
df = pd.DataFrame({
    "class": ["X", "X", "Y", "Y", "X", "Y"],
    "score": [80, np.nan, 70, 90, 60, np.nan],
})
df['score']=df['score'].fillna(df.groupby('class')['score'].transform('mean'))
df

  class  score
0     X   80.0
1     X   70.0
2     Y   70.0
3     Y   90.0
4     X   60.0
5     Y   80.0

In [1]:
# 13. Count by Category  [Service / pandas basics]
# Return how many products fall in each category.
import pandas as pd
products = pd.DataFrame({
    "product": ["P1", "P2", "P3", "P4", "P5"],
    "category": ["Food", "Tech", "Food", "Food", "Tech"],
})
products['category'].value_counts()

category
Food    3
Tech    2
Name: count, dtype: int64

In [3]:
# 14. Add a Flag Column  [AI screen / feature engineering]
# Add "is_adult": True if age >= 18, else False.
import pandas as pd
people = pd.DataFrame({
    "name": ["A", "B", "C", "D"],
    "age": [15, 22, 17, 30],
})

people['flag'] = people['age'].map(lambda x : True if x>=18 else False)
people['flag2'] = people['age'].map(lambda x : x>=18)
people

  name  age   flag  flag2
0    A   15  False  False
1    B   22   True   True
2    C   17  False  False
3    D   30   True   True

In [4]:
# 15. Average Per Group  [AI screen / groupby]
# Return the average salary per department.
import pandas as pd
staff = pd.DataFrame({
    "dept": ["IT", "HR", "IT", "HR", "IT"],
    "salary": [50000, 45000, 70000, 48000, 60000],
})
staff.groupby('dept').mean()

       salary
dept
HR    46500.0
IT    60000.0

In [9]:
# 1. Group Consecutive Numbers  [AI screen / logic]
# Split a sorted list into groups of consecutive runs.
# Example: [1, 2, 3, 5, 6, 8] -> [[1, 2, 3], [5, 6], [8]]
nums = [1, 2, 3, 5, 6, 8, 9, 10]
result = []
current_group = [nums[0]]
    
for i in range(1, len(nums)):
    if nums[i] == nums[i - 1] + 1:
        current_group.append(nums[i])
    else:
        result.append(current_group)
        current_group = [nums[i]]
        
result.append(current_group)
print(result)

[[1, 2, 3], [5, 6], [8, 9, 10]]

In [17]:
# 2. Count Word Frequency and Return Top 2  [AI screen / text]
# Return the two most frequent words with their counts.
# Example: "a b a c a b" -> [('a', 3), ('b', 2)]
from collections import Counter 
text = "the sun the moon the sun the star"
counts = Counter(text.lower().split())
sorted_dict = dict(sorted(counts.items(),key=lambda x : x[1],reverse=True))
[(k,sorted_dict[k]) for k in list(sorted_dict)[:2]]

[('the', 4), ('sun', 2)]

In [27]:
# 3. Check Balanced Brackets  [Service / logic]
# Return True if every opening bracket has a matching closing one, in order.
# Example: "(a[b]c)" -> True, "(a[b)c]" -> False
expr = "(a[b]{c})"
dict_brack = {")":"(","}":"{","]":"["}
stack = []

def brackets(expr):
    for char in expr:
        if char in dict_brack.values():
            stack.append(char)
        elif char in dict_brack:

            if not stack or stack.pop() != dict_brack[char]:
                return False
    return len(stack)==0

print(brackets(expr))
print(brackets(']a]'))

True
False

In [20]:
# 4. Flatten a Nested List (any depth)  [AI screen / logic]
# Flatten a list that may contain lists inside lists, to any depth.
# Example: [1, [2, [3, 4], 5], 6] -> [1, 2, 3, 4, 5, 6]
data = [1, [2, [3, 4], 5], [6, [7, [8]]]]
def flatten_list(nested_list):
    result = []
    for item in nested_list:
        # Check if the item is a list or tuple
        if isinstance(item, list):
            result.extend(flatten_list(item))
        else:
            result.append(item)
    return result
flatten_list(data)

[1, 2, 3, 4, 5, 6, 7, 8]

In [23]:
# 5. Find the Missing and Duplicate  [AI screen / logic]
# A list should hold 1 to n once each. One number is missing, one is duplicated.
# Return (duplicate, missing).
# Example: [1, 2, 2, 4], n=4 -> (2, 3)
arr = [1, 2, 3, 3, 5, 6]
n = 6
for i in range(1,n+1):
    if arr[i-1] != i:
        print((arr[i-1],i))

(3, 4)

In [28]:
# 1. Count Even Numbers  [Service / screening]
# Count how many even numbers are in a list.
# Example: [1, 2, 3, 4, 5, 6] -> 3
nums = [4, 7, 2, 9, 10, 15, 6]
sum([1 for i in nums if i%2==0])

4

In [29]:
# 2. Join Words With a Separator  [Service / string]
# Join a list of words into one string separated by " - ".
# Example: ["a", "b", "c"] -> "a - b - c"
words = ["data", "science", "python"]
" - ".join(words)

'data - science - python'

In [30]:
# 3. Find Max and Min  [Service / logic]
# Return the largest and smallest value as a tuple.
# Example: [3, 7, 1, 9] -> (9, 1)
values = [12, 5, 8, 21, 3]
print((max(values),min(values)))

(21, 3)

In [31]:
# 4. Count Characters Case-Insensitive  [Service / text]
# Count each character, treating upper and lower as the same.
# Example: "AaBb" -> {'a': 2, 'b': 2}
from collections import Counter
text = "HelloHELLO"
Counter(text.lower())

Counter({'l': 4, 'h': 2, 'e': 2, 'o': 2})

In [32]:
# 5. Sum Only Positive Numbers  [AI screen / logic]
# Return the sum of only the positive values.
# Example: [3, -2, 5, -1, 4] -> 12
data = [10, -5, 3, -8, 7, -2]
sum([i for i in data if i>0])

20

In [35]:
nums = [1, 2, 4, 5, 6, 8]

result = []
current = [nums[0]]           # start holding the first number

for i in range(1, len(nums)):
    if nums[i] == nums[i-1]+1:        # is nums[i] one more than the previous?
        current.append(nums[i])        # add it to current
    else:
        result.append(current)       # put current away, then
        current = [nums[i]]       # start a new group with nums[i]

result.append(current)        # put away the last group
print(result)

[[1, 2], [4, 5, 6], [8]]

In [38]:
# Can You Attend All Meetings?  [AI screen / logic]
# Given meeting time intervals, return True if a person can attend all of them,
# meaning none of them overlap.
# Example: [[0, 30], [35, 50], [60, 75]] -> True   (no clashes)
#          [[0, 30], [25, 50], [60, 75]] -> False  (first two overlap)
meetings = [[9, 10], [11, 12], [10, 11], [13, 15], [14, 16]]
# expected for this input: False  (13-15 and 14-16 overlap)
can_attend = True
sorted_meetings = sorted(meetings,key=lambda x : x[0])
for i in range(1,len(sorted_meetings)):
    prev_end = sorted_meetings[i-1][1]
    current_start = sorted_meetings[i][0]
    if current_start<prev_end:
        can_attend = False
        break
print(can_attend)

False

In [43]:
# Minimum Meeting Rooms  [AI screen / logic]
# Given meeting intervals, return how many rooms you need so that no two
# overlapping meetings share a room.
# Example: [[0, 30], [5, 10], [15, 20]] -> 2
#          (0-30 overlaps both 5-10 and 15-20, so you need a 2nd room)
meetings = [[1, 10], [2, 7], [3, 19], [8, 12], [10, 20], [11, 30]]

starts = sorted(m[0] for m in meetings)   # all start times
ends = sorted(m[1] for m in meetings)     # all end times

rooms = 0
max_rooms = 0
s = e = 0                                  # pointers into starts and ends

while s < len(starts):
    if starts[s] < ends[e]:                # a meeting starts before the next one ends
        rooms += 1                         # take a room
        s += 1
        max_rooms = max(max_rooms, rooms)
    else:                                   # a meeting ends first
        rooms -= 1                          # free a room
        e += 1

print(max_rooms)                            # 4

4

In [52]:
# Find Free Time  [AI screen / logic]
# Given busy meeting intervals in a day, return the gaps when the person is free.
# Assume the day runs from the end of one meeting to the start of the next.
# Example: [[1, 3], [5, 8], [10, 12]] -> [[3, 5], [8, 10]]
#          (free between 3 and 5, and between 8 and 10)
meetings = [[9, 11], [13, 14], [16, 18], [12, 13]]
# expected for this input: [[11, 12], [14, 16]]
meetings.sort(key=lambda x: x[0])
free_time = []
for i in range(1,len(meetings)):
    prev_end_time = meetings[i-1][1]
    current_start = meetings[i][0]
    if current_start > prev_end_time:
        free_time.append([prev_end_time,current_start])
print(free_time)

[[11, 12], [14, 16]]

In [58]:
# Total Busy Time  [AI screen / logic]
# Given meeting intervals that may overlap, return the total amount of time
# the person is busy. Overlapping time counts once, not twice.
# Example: [[1, 4], [2, 5], [7, 9]] -> 5
#          (1 to 5 is one merged busy block = 4, plus 7 to 9 = 2, total 6)
# wait, recheck: 1-5 is 4 units, 7-9 is 2 units, total = 6
meetings = [[1, 3], [2, 6], [8, 10], [15, 18]]
# expected for this input: 9  (1-6 = 5 units, 8-10 = 2, 15-18 = 3, total 10)
meetings.sort(key=lambda x: x[0])
merged=[meetings[0]]
for start,end in meetings[1:]:
    last = merged[-1]
    if start <= last[1]:
        last[1] = max(last[1],end)
    else:
        merged.append([start,end])
print(sum([abs(x[0]-x[1]) for x in merged]))

10

In [59]:
# Insert and Merge  [AI screen / logic]
# You have a sorted, non-overlapping list of intervals. Insert a new interval
# and merge if it overlaps anything.
# Example: existing [[1, 3], [6, 9]], new [2, 5] -> [[1, 5], [6, 9]]
#          (the new [2,5] overlaps [1,3], merges into [1,5])
intervals = [[1, 2], [3, 5], [6, 7], [8, 10], [12, 16]]
new = [4, 9]
# expected: [[1, 2], [3, 10], [12, 16]]
#          ([4,9] overlaps [3,5], [6,7], [8,10], all merge into [3,10])
intervals.append(new)
intervals.sort(key=lambda x: x[0])

merged = [intervals[0]]

for s,e in intervals[1:]:
    last = merged[-1]
    if s<=last[1]:
        last[1]=max(last[1],e)
    else:
        merged.append([s,e])
print(merged)

[[1, 2], [3, 10], [12, 16]]

In [3]:
# 1. Count Pairs With Given Difference  [Service / logic]
# Count how many pairs of numbers have a difference equal to k.
# Example: [1, 5, 3, 4, 2], k=2 -> 3  (3-1, 5-3, 4-2)
nums = [1, 5, 3, 4, 2, 7]
k = 2
num_set=set(nums)
count=0
for num in num_set:
    if num+k in num_set:
        count+=1
print(count)

4

In [4]:
# 2. First Non-Repeating Character  [Service / string]
# Return the first character in a string that does not repeat.
# Example: "swiss" -> "w"
from collections import Counter
s = "aabbccdde"
counts = Counter(s)

for char in counts:
    if counts[char] == 1:
        print(char)
        break

e

In [6]:
# 3. Move All Zeros to End  [Service / logic]
# Shift every zero to the end, keeping the order of the non-zero values.
# Example: [0, 1, 0, 3, 12] -> [1, 3, 12, 0, 0]
arr = [0, 1, 0, 3, 12, 0, 5]
[i for i in arr if i!=0] + [0]* arr.count(0)

[1, 3, 12, 5, 0, 0, 0]

In [18]:
# 4. Check Pangram  [Service / string]
# Return True if the sentence uses every letter of the alphabet at least once.
# Example: "The quick brown fox jumps over the lazy dog" -> True
import string
sentence = "Pack my box with five dozen liquor jugs"
set(string.ascii_lowercase) <= set([x for x in sentence.lower() if x.isalpha()])

True

In [17]:
# 5. Sum of Digits Until Single Digit  [Service / logic]
# Keep summing a number's digits until one digit is left.
# Example: 9875 -> 2  (9+8+7+5=29 -> 2+9=11 -> 1+1=2)
n = 99999

while len(str(n))>1:
    n=sum([int(x) for x in str(n)])
print(n)

9

In [21]:
# 1. Remove Duplicates Keeping Order  [Service / logic]
# Return the list with duplicates removed, first occurrence kept.
# Example: [3, 1, 3, 2, 1] -> [3, 1, 2]
nums = [4, 2, 4, 1, 2, 3, 1]
list(dict.fromkeys(nums))

[4, 2, 1, 3]

In [22]:
# 2. Count Vowels and Consonants  [Service / string]
# Return counts of vowels and consonants separately, letters only.
# Example: "hello world" -> vowels: 3, consonants: 7
from collections import Counter
s = "data science rocks"
counts = Counter(['Consonents' if i not in 'aeiou' else 'vowels' for i in s.lower() if i.isalpha()])
counts

Counter({'Consonents': 10, 'vowels': 6})

In [25]:
# 3. Find the Longest Word  [Service / text]
# Return the longest word in a sentence. Ties: return the first.
# Example: "I love machine learning" -> "learning"... wait, "machine" also 7, first wins
sentence = "AI is transforming the world"
# why-comment: how does max() break the tie, first or last?
print(max(sentence.split(),key=len))

transforming

In [28]:
# 4. Check if Anagram  [Service / string]
# Return True if two strings are anagrams.
# Example: "listen", "silent" -> True
a, b = "triangle", "integral"
# why-comment: what would break if you used set() instead of sorted or Counter?
sorted(a)==sorted(b)

True

In [30]:
# 5. Second Largest Unique  [Service / logic]
# Return the second largest DISTINCT value.
# Example: [5, 5, 4, 3] -> 4  (not 5)
values = [10, 10, 8, 8, 6, 3]
values_unique=list(set(values))
first=second=float('-inf')
for i in values_unique:
    if i > first:
        second = first
        first = i
    elif i > second and i!=first:
        second = i
print(second)
# why-comment: why does "distinct" change your approach?

8

In [32]:
# ============================================
# TIMED SET - 3 problems, 45 min - return, don't print
# ============================================

# Q1. Count Elements That Appear Exactly Once  [Service / logic]
# Return how many values appear exactly one time in the list.
# Example: [1, 2, 2, 3, 3, 3, 4] -> 2  (only 1 and 4 appear once)
from collections import Counter
def count_unique(nums):
    counts = Counter(nums)
    return sum([1 for i,j in counts.items() if j==1])
# test: count_unique([1, 2, 2, 3, 3, 3, 4]) -> 2
count_unique([1, 2, 2, 3, 3, 3, 4])

2

In [50]:
# Q2. Reverse Only Letters  [Service / string]
# Reverse the letters in a string but keep every non-letter in its place.
# Example: "a1b2c" -> "c1b2a"  (letters a,b,c reversed; digits stay put)
def reverse_letters(s):
    only_letter = [char for char in s if char.isalpha()]
    return "".join([only_letter.pop() if char.isalpha() else char for char in s])
        
    

# test: reverse_letters("a1b2c") -> "c1b2a"
reverse_letters("a1b2c")

'c1b2a'

In [35]:
# Q3. Group Scores by Pass/Fail  [AI screen / data handling]
# Given a dict of name -> score, return a dict with two lists: names who
# passed (score >= 40) and names who failed. Keep input order.
# Example: {"A": 80, "B": 30, "C": 55} -> {"pass": ["A","C"], "fail": ["B"]}
def group_by_result(scores):
    grouped = {'pass':[],'fail':[]}
    for name in scores:
        if scores[name]>=40:
            grouped['pass'].append(name)
        else:
            grouped['fail'].append(name)
    return grouped

# test: group_by_result({"A": 80, "B": 30, "C": 55}) -> {"pass": ["A","C"], "fail": ["B"]}
group_by_result({"A": 80, "B": 30, "C": 55})

{'pass': ['A', 'C'], 'fail': ['B']}

In [43]:
text='Mukundan'
popped_char = text[0]
text = text[:0] + text[0+1:]
text
popped_char = text[0]
text = text[:0] + text[0+1:]
text

'kundan'

In [48]:
lst = [1,2,4]
(lst.pop())
print(lst)

[1, 2]

In [57]:
# ============================================
# TIMED SET 2 - 3 problems, 45 min - return, don't print
# ============================================

# Q1. Most Frequent Character  [Service / string]
# Return the character that appears most often. On a tie, return the one
# that appears first in the string.
# Example: "aabbbcc" -> "b"
from collections import Counter
def most_frequent_char(s):
    counts = Counter(s)
    return ([k for k,v in counts.items() if v==max(counts.values())][0])

# test: most_frequent_char("aabbbcc") -> "b"
most_frequent_char("aabbbcc")

'b'

In [59]:
# Q2. Sum of Unique Numbers  [Service / logic]
# Return the sum of values that appear exactly once in the list.
# Example: [1, 2, 2, 3, 4, 4] -> 4  (only 1 and 3 are unique; 1+3=4)
from collections import Counter
def sum_of_unique(nums):
    counts = Counter(nums)
    return sum([k for k,v in counts.items() if v==1])

# test: sum_of_unique([1, 2, 2, 3, 4, 4]) -> 4
sum_of_unique([1, 2, 2, 3, 4, 4])

4