In [2]:
# 1. Count Words  [Service / string]
# Return how many words are in a sentence.
# Example: "I am learning AI" -> 4
def word_count(s):
    return len(s.split())
print(word_count("I am learning AI"))# -> 4 ; 
print(word_count(""))# -> 0

4
0

In [8]:
# 2. Swap First and Last  [Service / logic]
# Return the list with its first and last elements swapped.
# Example: [1,2,3,4] -> [4,2,3,1]
def swap_ends(nums):
    nums[0],nums[-1] = nums[-1],nums[0]
    return nums
# test: swap_ends([1,2,3,4]) -> [4,2,3,1] ; swap_ends([5]) -> [5]
print(swap_ends([1,2,3,4]))
print(swap_ends([5]))

[4, 2, 3, 1]
[5]

In [10]:
# 3. Count Vowels  [Service / string]
# Return how many vowels (a,e,i,o,u) are in a string, case-insensitive.
# Example: "Hello" -> 2
def count_vowels(s):
    return sum([1 for i in s.lower() if i in 'aeiou'])
print(count_vowels("Hello"))# -> 2 ; 
print(count_vowels("xyz"))# -> 0

2
0

In [11]:
# 4. Flatten One Level  [Service / logic]
# Flatten a list of lists ONE level deep.
# Example: [[1,2],[3,4],[5]] -> [1,2,3,4,5]
def flatten_one(lsts):
    return [x for i in lsts for x in i]
print(flatten_one([[1,2],[3,4],[5]]))# -> [1,2,3,4,5]

[1, 2, 3, 4, 5]

In [13]:
# 5. Reverse Each Word  [Service / string]
# Reverse the letters of each word, keep word order.
# Example: "hello world" -> "olleh dlrow"
def reverse_each_word(s):
    return " ".join([i[::-1] for i in s.split()])
print(reverse_each_word("hello world"))# -> "olleh dlrow"

olleh dlrow

In [15]:
# 6. Array Mean and Std  [AI screen / numpy]
# Return (mean, std) of a 1D array as a tuple.
import numpy as np
arr = np.array([10, 20, 30, 40, 50])
print((arr.mean(),arr.std()))

(np.float64(30.0), np.float64(14.142135623730951))

In [17]:
# 7. Count Values Below Mean  [AI screen / data handling]
# Return HOW MANY elements are below the mean. (a count)
import numpy as np
data = np.array([10, 20, 30, 40, 50])
(data<data.mean()).sum()

np.int64(2)

In [18]:
# 8. Reverse an Array  [AI screen / numpy]
# Return the array reversed.
import numpy as np
a = np.array([1, 2, 3, 4, 5])
a[::-1]

array([5, 4, 3, 2, 1])

In [19]:
# 9. Element-wise Max of Two Arrays  [AI screen / numpy]
# Return an array of the element-wise maximum of two arrays.
# Example: [1,5,2], [3,1,4] -> [3,5,4]
import numpy as np
x = np.array([1, 5, 2])
y = np.array([3, 1, 4])
np.max((x,y),axis=0)

array([3, 5, 4])

In [20]:
# 10. Row Means of a Matrix  [AI screen / numpy]
# Return the mean of each ROW. (axis check!)
import numpy as np
grid = np.array([[1, 2, 3], [4, 5, 6]])
np.mean(grid,axis=1)

array([2., 5.])

In [22]:
# 11. Add a Computed Column  [AI screen / pandas]
# Add "total" = price * qty.
import pandas as pd
df = pd.DataFrame({"item": ["a","b","c"], "price": [10,20,5], "qty": [2,1,4]})
df['total'] = df['price']*df['qty']
df

  item  price  qty  total
0    a     10    2     20
1    b     20    1     20
2    c      5    4     20

In [23]:
# 12. Filter Two Conditions  [AI screen / pandas]
# Return rows where age > 25 AND city == "Chennai".
import pandas as pd
people = pd.DataFrame({
    "name": ["A","B","C","D"],
    "age": [30, 22, 28, 35],
    "city": ["Chennai","Chennai","Mumbai","Chennai"],
})

people[(people['age']>25)&(people['city']=='Chennai')]

  name  age     city
0    A   30  Chennai
3    D   35  Chennai

In [25]:
# 13. Count Per Group  [AI screen / groupby]
# Return how many employees per department.
import pandas as pd
emp = pd.DataFrame({"dept": ["IT","HR","IT","IT","HR"]})
emp['dept'].value_counts()

dept
IT    3
HR    2
Name: count, dtype: int64