In [3]:
# 1. Reverse Integer  [Service / screening]
# Return the integer with its digits reversed. Preserve the sign.
# 1234 -> 4321 ; -520 -> -25
def reverse_int(n):
    sign = -1 if n < 0 else 1
    reversed_num = int(str(abs(n))[::-1])
    return sign * reversed_num
    
print(reverse_int(1234))# -> 4321 ; 
print(reverse_int(-520))# -> -25 ; 
print(reverse_int(0))# -> 0

4321
-25
0

In [6]:
# 2. Palindrome Number  [Service / screening]
# Return True if the integer reads the same forwards and backwards.
# 121 -> True ; 123 -> False ; negatives are never palindromes
def is_palindrome_num(n):
    return str(n) == str(n)[::-1]
print(is_palindrome_num(121))# -> True ; 
print(is_palindrome_num(123))# -> False ; 
print(is_palindrome_num(-121))# -> False

True
False
False

In [10]:
# 3. Prime Check  [Service / screening]
# Return True if n is prime (n >= 2). 1 and below are not prime.
# 7 -> True ; 9 -> False
def is_prime(n):
    if n < 2:
        return False
    if n in (2, 3):
        return True
    if n % 2 == 0 or n % 3 == 0:
        return False
    i = 5
    while i * i <= n:
        if n % i == 0 or n % (i + 2) == 0:
            return False
        i += 6
    return True
print(is_prime(7))# -> True ; 
print(is_prime(9))# -> False ; 
print(is_prime(1))# -> False ; 
print(is_prime(2))# -> True

True
False
False
True

In [13]:
# 4. Fibonacci Series  [Service / screening]
# Return a list of the first n Fibonacci numbers starting 0, 1.
# 5 -> [0,1,1,2,3]
def fib(n):
    if n <= 0:
        return []
    if n == 1:
        return [0]
    res = [0, 1]
    while len(res) < n:
        res.append(res[-1] + res[-2])
    return res
    
print(fib(5))# -> [0,1,1,2,3] ; 
print(fib(1))# -> [0] ; 
print(fib(0))# -> []

[0, 1, 1, 2, 3]
[0]
[]

In [17]:
# 5. Armstrong Number  [Service / screening]
# A 3-digit number equal to the sum of the cubes of its digits.
# Return True/False. 153 -> True (1+125+27) ; 154 -> False
def is_armstrong(n):
    return n == sum([int(i)**3 for i in str(n)])
    
print(is_armstrong(153))# -> True ; 
print(is_armstrong(154))# -> False ; 
print(is_armstrong(370))# -> True

True
False
True

In [28]:
# 6. GCD  [Service / screening]
# Return the greatest common divisor of a and b (Euclid's algorithm).
# 12, 18 -> 6
def gcd(a, b):
    while b != 0:
        a,b = b, a % b
    return a
print(gcd(12,18))# -> 6 ; 
print(gcd(7,13))# -> 1 ; 
print(gcd(0,5))# -> 5

6
1
5

In [31]:
# 7. Count Vowels and Consonants  [Service / screening]
# Return a tuple (vowels, consonants). Count letters only, case-insensitive.
# "Hello World" -> (3, 7)
def count_vc(s):
    vowels = sum([1 for i in s if i.lower() in 'aeiou' and i.isalpha()])
    cons = sum([1 for i in s if i.lower() not in 'aeiou' and i.isalpha()])
    return (vowels,cons)
print(count_vc("Hello World"))# -> (3, 7) ; 
print(count_vc("123"))# -> (0, 0)

(3, 7)
(0, 0)

In [34]:
# 8. Anagram Check  [Service / screening]
# Return True if a and b are anagrams, case-insensitive.
# "Listen", "Silent" -> True
def is_anagram(a, b):
    return sorted(a.lower()) == sorted(b.lower())
    
print(is_anagram("Listen","Silent"))# -> True ; 
print(is_anagram("abc","abd"))# -> False

True
False

In [38]:
# 9. Factorial (iterative, no library)  [Service / screening]
# Return n! using a loop. 0! is 1.
# 5 -> 120
def factorial(n):
    if n == 0:
        return 1
    count=1
    for i in range(1,n+1):
        count*=i
    return count
print(factorial(5))# -> 120 ; 
print(factorial(0))# -> 1

120
1

In [41]:
# 10. Second Largest  [Service / screening]
# Return the second largest DISTINCT value, or None if there isn't one.
# [4,1,7,7,3] -> 4
def second_largest(nums):
    first = second = float('-inf')
    for i in set(nums):
        if i > first:
            second = first
            first = i
        elif i > second and i != first:
            second = i
    return second if second != float('-inf') else None
print(second_largest([4,1,7,7,3]))# -> 4 ; 
print(second_largest([5,5]))# -> None

4
None

In [43]:
# 1. Min-Max Normalize  [AI interview / numpy]
# Scale a 1D array to the 0-1 range: (x - min) / (max - min).
import numpy as np
a = np.array([10, 20, 30, 40, 50])
(a - a.min()) / (a.max() - a.min())

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [45]:
# 2. Z-Score Standardize  [AI interview / numpy]
# Return (x - mean) / std.
import numpy as np
a = np.array([2.0, 4.0, 6.0, 8.0])
(a - a.mean()) / a.std()

array([-1.34164079, -0.4472136 ,  0.4472136 ,  1.34164079])

In [46]:
# 3. ReLU  [AI interview / numpy]
# Apply ReLU: replace every negative value with 0, keep the rest.
import numpy as np
a = np.array([-3, 1, -5, 7, 0])
a[a < 0] = 0
a

array([0, 1, 0, 7, 0])

In [47]:
# 4. Row-wise Mean  [AI interview / numpy]
# Return the mean of each ROW.
import numpy as np
grid = np.array([[1, 2, 3], [4, 5, 6]])
np.mean(grid,axis=1)

array([2., 5.])

In [48]:
# 5. Column Max  [AI interview / numpy]
# Return the maximum of each COLUMN.
import numpy as np
grid = np.array([[1, 8, 3], [5, 2, 9]])
np.max(grid,axis=0)

array([5, 8, 9])

In [49]:
# 6. Index of Max (argmax)  [AI interview / numpy]
# Return the INDEX of the largest value in a 1D array.
import numpy as np
a = np.array([3, 9, 2, 9, 1])
np.argmax(a)

np.int64(1)

In [51]:
# 7. Matrix Multiply  [AI interview / numpy]
# Return the matrix product of A and B.
import numpy as np
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])
np.matmul(A,B)

array([[19, 22],
       [43, 50]])

In [53]:
np.dot(A,B)

array([[19, 22],
       [43, 50]])

In [54]:
# 8. Reshape to 2D  [AI interview / numpy]
# Reshape a length-12 array into a 3x4 matrix.
import numpy as np
a = np.arange(12)
a.reshape((3,4))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [56]:
# 9. Count Above Threshold  [AI interview / numpy]
# Return HOW MANY values are greater than the mean. (a count)
import numpy as np
a = np.array([10, 20, 30, 40, 50])
(a > a.mean()).sum()

np.int64(2)

In [57]:
# 10. Euclidean Distance  [AI interview / numpy]
# Return the Euclidean distance between two vectors:
# sqrt(sum((x - y)^2)).
import numpy as np
x = np.array([1.0, 2.0, 3.0])
y = np.array([4.0, 6.0, 3.0])
np.sqrt(np.sum((x - y) ** 2))

np.float64(5.0)

In [60]:
# 11. Filter Rows  [AI interview / pandas]
# Return rows where age >= 30, columns name and age only.
import pandas as pd
df = pd.DataFrame({"name":["A","B","C","D"], "age":[25,35,30,40], "city":["P","Q","R","S"]})
df[df['age']>=30][['name','age']]

  name  age
1    B   35
2    C   30
3    D   40

In [61]:
# 12. Group Mean  [AI interview / pandas]
# Return the average salary per dept, as a DataFrame (reset index),
# columns "dept" and "avg_salary".
import pandas as pd
emp = pd.DataFrame({"dept":["IT","IT","HR","HR"], "salary":[70000,90000,50000,60000]})
emp.groupby('dept',as_index=False).agg(avg_salary = ('salary','mean'))

  dept  avg_salary
0   HR     55000.0
1   IT     80000.0

In [64]:
# 13. Value Counts  [AI interview / pandas]
# Return the count of each label, highest count first.
import pandas as pd
df = pd.DataFrame({"label":["cat","dog","cat","cat","dog","bird"]})
df['label'].value_counts().sort_values(ascending=False)

label
cat     3
dog     2
bird    1
Name: count, dtype: int64

In [65]:
# 14. Fill Missing with Mean  [AI interview / pandas]
# Fill NaN in "score" with the column mean. Return the full df.
import pandas as pd, numpy as np
df = pd.DataFrame({"name":["A","B","C","D"], "score":[10.0, np.nan, 30.0, np.nan]})
df['score'] = df['score'].fillna(df['score'].mean())
df

  name  score
0    A   10.0
1    B   20.0
2    C   30.0
3    D   20.0

In [66]:
# 15. Label Encode  [AI interview / pandas]
# Add a column "target" mapping "yes"->1 and "no"->0. Return the df.
import pandas as pd
df = pd.DataFrame({"id":[1,2,3], "churn":["yes","no","yes"]})
mapping = {"yes":1,"no":0}
df['target'] = df['churn'].map(mapping)
df

   id churn  target
0   1   yes       1
1   2    no       0
2   3   yes       1

In [67]:
# 16. Top 3 by Value  [AI interview / pandas]
# Return the 3 highest-salary rows, columns name and salary, highest first.
import pandas as pd
emp = pd.DataFrame({"name":["A","B","C","D","E"], "salary":[50,90,70,60,85]})
emp.sort_values('salary',ascending=False).head(3)

  name  salary
1    B      90
4    E      85
2    C      70

In [76]:
# 17. Merge DataFrames  [AI interview / pandas]
# Left-merge orders to customers on cust_id; orders with no match get
# name "Unknown". Return columns order_id, name, amount.
import pandas as pd
customers = pd.DataFrame({"cust_id":[1,2], "name":["Arjun","Priya"]})
orders = pd.DataFrame({"order_id":[101,102,103], "cust_id":[1,2,9], "amount":[500,300,700]})

pd.merge(orders,customers,on='cust_id',how='left').fillna('Unknown')[['order_id','amount','name']]

   order_id  amount     name
0       101     500    Arjun
1       102     300    Priya
2       103     700  Unknown

In [69]:
# 18. Pivot Table  [AI interview / pandas]
# Rows = region, columns = product, values = sum of amount, missing as 0.
import pandas as pd
sales = pd.DataFrame({
    "region":["N","N","S","S"], "product":["x","y","x","x"], "amount":[10,20,30,40]
})

pd.pivot_table(data=sales,index='region',columns='product',aggfunc='sum',values='amount',fill_value=0)

product   x   y
region
N        10  20
S        70   0

In [77]:
# 19. Correlation  [AI interview / pandas]
# Return the correlation between "hours" and "score" (a single number).
import pandas as pd
df = pd.DataFrame({"hours":[1,2,3,4,5], "score":[52,58,61,69,74]})
df['hours'].corr(df['score'])

np.float64(0.9929674489269132)

In [74]:
# 20. Group Then Filter  [AI interview / pandas]
# Return average salary per dept, keep only depts with average > 55000,
# as a DataFrame (reset index), columns "dept" and "avg_salary".
import pandas as pd
emp = pd.DataFrame({"dept":["IT","IT","HR","HR","Fin"], "salary":[80000,70000,50000,48000,90000]})
grouped = emp.groupby('dept',as_index=False).agg(avg_salary=('salary','mean'))
grouped[grouped['avg_salary']>55000].reset_index(drop='index')

  dept  avg_salary
0  Fin     90000.0
1   IT     75000.0

In [39]:
# 1. Roman to Integer  [AI screen / string]
# Convert a Roman numeral to an integer. Values: I=1,V=5,X=10,L=50,C=100,D=500,M=1000.
# If a smaller value sits before a larger one, subtract it (IV=4, IX=9).
# "LVIII" -> 58 ; "MCMXCIV" -> 1994
# Idea: walk left to right; if the current value is less than the NEXT one, subtract it, else add it.
def roman_to_int(s):
    romans = {'I':1,'V':5,'X':10,'L':50,'C':100,'D':500,'M':1000}
    int_val = 0
    for i in range(len(s)):
        if i+1 < len(s) and romans[s[i]] < romans[s[i+1]]:
            int_val-=romans[s[i]]
        else:
            int_val+=romans[s[i]]
    return int_val
print(roman_to_int("LVIII"))# -> 58 ; 
print(roman_to_int("MCMXCIV"))# -> 1994 ; 
print(roman_to_int("III"))# -> 3

58
1994
3

In [25]:
# 2. Best Time to Buy and Sell Stock  [AI screen / logic]
# prices[i] is the price on day i. Return the max profit from one buy then
# one later sell. If no profit is possible, return 0.
# [7,1,5,3,6,4] -> 5   (buy at 1, sell at 6)
# Idea: track the lowest price seen so far; at each day, profit = price - min_so_far, keep the best.
def max_profit(prices):
    min_price = float('inf')
    max_p = 0
    for i in prices:
        if i < min_price:
            min_price = i
        elif i-min_price > max_p:
            max_p = i - min_price
    return max_p
print(max_profit([7,1,5,3,6,4]))# -> 5 ; 
print(max_profit([7,6,4,3,1]))# -> 0 ; 
print(max_profit([]))# -> 0

5
0
0

In [29]:
# 3. Single Number  [AI screen / logic]
# Every element appears twice except one. Return the one that appears once.
# [4,1,2,1,2] -> 4
# Idea: XOR everything (a ^ a == 0), or count and return the odd one out.
def single_number(nums):
    for i in nums:
        if nums.count(i) == 1:
            return i
    return None
print(single_number([4,1,2,1,2]))# -> 4 ; 
print(single_number([1]))# -> 1

4
1

In [34]:
# 4. First Unique Character Index  [AI screen / string]
# Return the INDEX of the first non-repeating character, or -1 if none.
# "leetcode" -> 0 ; "aabb" -> -1
# Idea: count all chars, then scan left to right for the first with count 1.
def first_uniq_index(s):
    for idx,char in enumerate(s):
        if s.count(char) == 1:
            return idx
    return -1
print(first_uniq_index("leetcode"))# -> 0 ; 
print(first_uniq_index("loveleetcode"))# -> 2 ; 
print(first_uniq_index("aabb"))# -> -1

0
2
-1

In [38]:
# 5. Plus One  [AI screen / logic]
# digits is a number as a list of digits. Add 1 and return the new digit list.
# [1,2,3] -> [1,2,4] ; [1,9,9] -> [2,0,0] ; [9,9] -> [1,0,0]
# Idea: go right to left adding the carry; if a digit was 9 it becomes 0 and carries.
def plus_one(digits):
    num = str(int("".join([str(x) for x in digits]))+1)
    return [int(x) for x in num]
print(plus_one([1,2,3]))# -> [1,2,4] ; 
print(plus_one([1,9,9]))# -> [2,0,0] ; 
print(plus_one([9,9]))# -> [1,0,0]

[1, 2, 4]
[2, 0, 0]
[1, 0, 0]

In [42]:
# 1. Climbing Stairs  [AI screen / logic]
# You climb 1 or 2 steps at a time. Return how many distinct ways to reach
# the top of n steps. n=3 -> 3  (1+1+1, 1+2, 2+1)
# Idea: ways(n) = ways(n-1) + ways(n-2). It's Fibonacci. Build it up iteratively.
def climb(n):
    if n <= 1:
        return 1
    a, b = 1, 1
    for _ in range(2, n + 1):
        a, b = b, a + b
    return b
print(climb(3))# -> 3 ; 
print(climb(5))# -> 8 ; 
print(climb(1))# -> 1 ; climb(0) -> 1

3
8
1