In [3]:
# 1. Sum of Digits  [Service / logic]
# Return the sum of the digits of a non-negative integer.
# 1234 -> 10
def digit_sum(n):
    return sum([int(x) for x in str(n)])
print(digit_sum(1234))# -> 10 ; 
print(digit_sum(0))# -> 0

10
0

In [5]:
# 2. Count Words  [Service / string]
# Return how many words are in a sentence.
# "I am learning" -> 3
def word_count(s):
    return len(s.split())
print(word_count("I am learning"))# -> 3 ; 
print(word_count(""))# -> 0

3
0

In [8]:
# 3. Remove Vowels  [Service / string]
# Return the string with all vowels removed (case-insensitive).
# "Hello" -> "Hll"
import re
def remove_vowels(s):
    without_vowels = re.findall(r'[^aeiouAEIOU]',s)
    return "".join(without_vowels)
print(remove_vowels("Hello"))# -> "Hll" ; 
print(remove_vowels("xyz"))# -> "xyz"

Hll
xyz

In [12]:
# 4. Second Smallest  [AI screen / logic]
# Return the second smallest DISTINCT value, or None if there isn't one.
# [4,1,1,3] -> 3
def second_smallest(nums):
    first = second = float('inf')
    for i in set(nums):
        if i < first:
            second = first
            first = i
        elif i < second and i != first:
            second = i
    return second if second != float('inf') else None
print(second_smallest([4,1,1,3]))# -> 3 ; 
print(second_smallest([2,2]))# -> None ; 
print(second_smallest([5,1,2,3]))# -> 2

3
None
2

In [15]:
# 5. Pairs Summing to Target  [AI screen / logic]
# Return the COUNT of index pairs (i < j) where nums[i] + nums[j] == target.
# [1,2,3,2], 4 -> 2
def count_pairs(nums, target):
    count = 0
    for i in range(len(nums)):
        for j in range(i,len(nums)):
            if nums[i] + nums[j] == target and i != j:
                count+=1
    return count
            
print(count_pairs([1,2,3,2], 4))# -> 2 ; 
print(count_pairs([2,2,2], 4))# -> 3

2
3

In [17]:
# 6. Flatten Deep  [AI screen / recursion]
# Flatten a nested list of ANY depth, left to right.
# [1,[2,[3,4]],5] -> [1,2,3,4,5]
def flatten_deep(x):
    result = []
    for i in x:
        if isinstance(i,list):
            result.extend(flatten_deep(i))
        else:
            result.append(i)
    return result
print(flatten_deep([1,[2,[3,4]],5]))# -> [1,2,3,4,5] ; 
print(flatten_deep([]))# -> []

[1, 2, 3, 4, 5]
[]

In [19]:
# 7. Count Above Mean  [AI screen / data handling]
# Return HOW MANY values are strictly above the mean. (a count)
import numpy as np
data = np.array([10, 20, 30, 40, 50])
(data > data.mean()).sum()

np.int64(2)

In [20]:
# 8. Clip to Bounds  [AI screen / numpy]
# Return the array with values clipped to [0, 100].
import numpy as np
a = np.array([-5, 50, 150, 0, 100])
np.clip(a,0,100)

array([  0,  50, 100,   0, 100])

In [25]:
# 9. Group Total, Filter, Sort  [AI screen / pandas]
# Total amount per region, keep only totals >= 100, sorted descending,
# as a DataFrame (reset index), columns "region" and "total".
import pandas as pd
sales = pd.DataFrame({
    "region": ["N","S","N","E","S","N"],
    "amount": [60, 40, 80, 200, 70, 30],
})
grouped = sales.groupby('region',as_index=False).agg(total = ('amount','sum'))
grouped[grouped['total']>=100].sort_values('total',ascending=False).reset_index(drop='index')

  region  total
0      E    200
1      N    170
2      S    110

In [24]:
# 10. Fill Missing by Group  [AI screen / pandas]
# Fill NaN in "score" with the mean of that row's own "team". Return the df.
import pandas as pd, numpy as np
df = pd.DataFrame({
    "team": ["A","A","B","B"],
    "score": [10.0, np.nan, 20.0, np.nan],
})
df['score'] = df['score'].fillna(df.groupby('team')['score'].transform('mean'))
df

  team  score
0    A   10.0
1    A   10.0
2    B   20.0
3    B   20.0

In [30]:
# 1. FizzBuzz  [screening]
# Return a list 1..n: "Fizz" if divisible by 3, "Buzz" if by 5,
# "FizzBuzz" if both, else the number as a string.
def fizzbuzz(n):
    result = []
    for i in range(1,n+1):
        if n == 15:
            result.append('FizzBuzz')
        elif i %3 == 0:
            result.append('Fizz')
        elif i %5 == 0:
            result.append('Buzz')
        else:
            result.append(i)
    return result
print(fizzbuzz(5))# -> ["1","2","Fizz","4","Buzz"] ; 
print(fizzbuzz(15)[-1])# -> "FizzBuzz"

[1, 2, 'Fizz', 4, 'Buzz']
FizzBuzz

In [33]:
# 2. Reverse Words  [string]
# Reverse the order of words, collapse extra spaces to single spaces.
# "  the quick  fox " -> "fox quick the"
def reverse_words(s):
    return " ".join((s.split()[::-1]))
print(reverse_words("  the quick  fox "))# -> "fox quick the" ; 
print(reverse_words(""))# -> ""

fox quick the

In [50]:
# 3. Two Sum (indices)  [logic]
# Return indices of the two numbers that add to target. One solution.
# [2,7,11,15], 9 -> [0,1]
def two_sum(nums, target):
    seen = {}
    for i, num in enumerate(nums):
        complement = target - num
        if complement in seen:
            return [seen[complement], i]
        seen[num] = i
print(two_sum([2,7,11,15], 9))# -> [0,1] ; 
print(two_sum([3,2,4], 6))# -> [1,2]

[0, 1]
[1, 2]

In [36]:
# 4. Most Frequent  [dict]
# Return the most frequent element; on a tie, the one appearing first.
# [1,2,2,3,3] -> 2
def most_frequent(nums):
    result = {k:nums.count(k) for k in nums}
    for i in result:
        if result[i] == max(result.values()):
            return i
        
print(most_frequent([1,2,2,3,3]))# -> 2 ; 
print(most_frequent([4]))# -> 4

2
4

In [42]:
# 5. Compress String  [string]
# Run-length encode: "aaabbc" -> "a3b2c1".
def compress(s):
    if s == "":
        return ""
    count = 1 
    result = []
    current=s[0]
    for i in range(1,len(s)):
        if s[i] == s[i-1]:
            count+=1
        else:
            result.append(current+str(count))
            count=1
            current=s[i]
    result.append(current+str(count))
    return "".join(result)
print(compress("aaabbc"))# -> "a3b2c1" ; 
print(compress(""))# -> "" ; 
print(compress("x"))# -> "x1"

a3b2c1

x1

In [44]:
# 6. Count in Range  [numpy / data handling]
# Return HOW MANY values are between 20 and 80 inclusive. (a count)
import numpy as np
data = np.array([10, 20, 50, 80, 90, 5])
((data <= 80) & (data >= 20)).sum()

np.int64(3)

In [47]:
# 7. Highest Paid Per Dept  [pandas]
# Return the single highest-paid employee per dept, columns name, dept, salary.
import pandas as pd
emp = pd.DataFrame({
    "name": ["A","B","C","D","E"],
    "dept": ["IT","IT","HR","HR","HR"],
    "salary": [70000, 90000, 50000, 80000, 60000],
})
emp.sort_values("salary", ascending=False).groupby("dept", as_index=False).first()

  dept name  salary
0   HR    D   80000
1   IT    B   90000

In [48]:
# 8. Group, Filter, Sort  [pandas]
# Total amount per region, keep only totals >= 100, sorted descending,
# as a DataFrame (reset index), columns "region" and "total".
import pandas as pd
sales = pd.DataFrame({
    "region": ["N","S","N","E","S","N"],
    "amount": [60, 40, 80, 200, 70, 30],
})
grouped = sales.groupby('region',as_index=False).agg(total = ('amount','sum'))
grouped[grouped['total']>=100].sort_values('total',ascending=False).reset_index(drop='index')

  region  total
0      E    200
1      N    170
2      S    110

In [55]:
# 1. Count Vowels and Consonants  [screening]
# Return a tuple (vowels, consonants). Letters only, case-insensitive.
def count_vc(s):
    vowels = sum([1 for i in s if i.lower() in 'aeiou' and i.isalpha()])
    cons = sum([1 for i in s if i.lower() not in 'aeiou' and i.isalpha()])
    return (vowels,cons)
print(count_vc("Hello World"))# -> (3, 7) ; 
print(count_vc("123"))# -> (0, 0)

(3, 7)
(0, 0)

In [59]:
# 2. Palindrome Check  [string]
# True if the string is a palindrome, case-insensitive, letters/digits only.
import re
def is_palindrome(s):
    s = "".join(re.findall(r'[a-zA-Z0-9]+',s))
    s = s.lower()
    return s == s[::-1]
print(is_palindrome("A man, a plan, a canal: Panama")) #-> True ; 
print(is_palindrome("abc"))# -> False

True
False

In [61]:
# 3. Missing Number  [logic]
# nums holds distinct numbers 0..n with one missing. Return it.
def missing_number(nums):
    n = len(nums)
    expected_sum = n * (n + 1) // 2
    return expected_sum - sum(nums)
print(missing_number([3,0,1]))#-> 2 ; 
print(missing_number([0,1]))# -> 2 ; missing_number([0]) -> 1

2
2

In [63]:
# 4. Group by First Letter  [dict]
# Return a dict: first letter -> list of words starting with it, original order.
from collections import defaultdict
def group_by_first(words):
    grouped = defaultdict(list)
    for i in words:
        grouped[i[0]].append(i)
    return dict(grouped)
print(group_by_first(["apple","banana","avocado"]))# -> {"a":["apple","avocado"], "b":["banana"]}

{'a': ['apple', 'avocado'], 'b': ['banana']}

In [64]:
# 5. Move Zeros  [logic]
# Move all 0s to the end, keep order of non-zero values (negatives included).
def move_zeros(nums):
    return [i for i in nums if i !=0] + [0]*nums.count(0)
print(move_zeros([0,-1,0,3,-2]))# -> [-1,3,-2,0,0]

[-1, 3, -2, 0, 0]

In [65]:
# 6. Standardize  [numpy]
# Return the array standardized: (x - mean) / std.
import numpy as np
a = np.array([2.0, 4.0, 6.0, 8.0])
(a - a.mean()) / a.std()

array([-1.34164079, -0.4472136 ,  0.4472136 ,  1.34164079])

In [66]:
# 7. Average Per Group  [pandas]
# Average score per class, as a DataFrame (reset index),
# columns "class" and "avg_score".
import pandas as pd
students = pd.DataFrame({"class":["X","Y","X","Y","X"], "score":[80,70,90,60,100]})
students.groupby('class',as_index=False).agg(avg_score=('score','mean'))

  class  avg_score
0     X       90.0
1     Y       65.0

In [74]:
# 8. Days Between, Filter  [pandas]
# Add "days" = days between start and end (date strings), then return only
# rows where days > 5. Columns: all.
import pandas as pd
trips = pd.DataFrame({
    "trip": ["a","b","c"],
    "start": ["2024-01-01","2024-03-01","2024-05-10"],
    "end":   ["2024-01-03","2024-03-15","2024-05-20"],
})
trips['start'] = pd.to_datetime(trips['start'])
trips['end'] = pd.to_datetime(trips['end'])
trips["days"] = (trips["end"] - trips["start"]).dt.days
result = trips[trips["days"] > 5]
result

  trip      start        end  days
1    b 2024-03-01 2024-03-15    14
2    c 2024-05-10 2024-05-20    10

In [4]:
# 1. Factorial (iterative)  [screening]
# Return n! using a loop. 0! is 1.
def factorial(n):
    if n == 0:
        return 1
    fact_n = 1
    for i in range(1,n+1):
        fact_n*=i
    return fact_n
print(factorial(5))# -> 120 ; 
print(factorial(0))# -> 1

120
1

In [6]:
# 2. Title Case  [string]
# Capitalize the first letter of each word, lowercase the rest.
# "hELLO wORLD" -> "Hello World"
def title_case(s):
    return " ".join([i[0].upper()+i[1:] for i in s.lower().split()])
print(title_case("hELLO wORLD"))# -> "Hello World" ; 
print(title_case(""))# -> ""

Hello World

In [8]:
# 3. Dedupe Keep Order  [logic]
# Remove duplicates, keep first-occurrence order.
# [3,1,3,2,1] -> [3,1,2]
def dedupe(nums):
    seen = []
    for i in nums:
        if i not in seen:
            seen.append(i)
    return seen
print(dedupe([3,1,3,2,1]))# -> [3,1,2] ; 
print(dedupe([]))# -> []

[3, 1, 2]
[]

In [13]:
# 4. First Unique Character Index  [string]
# Return the index of the first non-repeating char, or -1 if none.
# "leetcode" -> 0 ; "aabb" -> -1
def first_uniq_index(s):
    for idx,i in enumerate(s):
        if s.count(i) == 1:
            return idx
    return -1
print(first_uniq_index("leetcode"))# -> 0 ; 
print(first_uniq_index("loveleetcode"))# -> 2 ; 
print(first_uniq_index("aabb"))# -> -1

0
2
-1

In [20]:
# 5. Max Subarray Sum  [logic]
# Largest sum of any contiguous non-empty subarray.
# [-2,1,-3,4,-1,2,1,-5,4] -> 6
def max_subarray(nums):
    current_sum = max_sum = nums[0]
    for num in nums[1:]:
        current_sum = max(num, current_sum + num)
        max_sum = max(max_sum, current_sum)
    return max_sum
print(max_subarray([-2,1,-3,4,-1,2,1,-5,4]))# -> 6 ; max_subarray([-1,-2]) -> -1

6

In [16]:
# 6. Normalize to Sum 1  [numpy]
# Return the array divided by its total so it sums to 1.
import numpy as np
a = np.array([10.0, 20.0, 70.0])
a/a.sum()

array([0.1, 0.2, 0.7])

In [17]:
# 7. Value Counts  [pandas]
# Return the count of each label, highest count first.
import pandas as pd
df = pd.DataFrame({"label": ["cat","dog","cat","cat","dog","bird"]})
df.value_counts()

label
cat      3
dog      2
bird     1
Name: count, dtype: int64

In [18]:
# 8. Label Encode  [pandas]
# Add a column "target" mapping "yes"->1, "no"->0. Return the df.
import pandas as pd
df = pd.DataFrame({"id":[1,2,3], "churn":["yes","no","yes"]})
dicts = {'yes':1,'no':0}
df['target'] = df['churn'].map(dicts)
df

   id churn  target
0   1   yes       1
1   2    no       0
2   3   yes       1

In [91]:
# 1. Word Frequency  [fundamentals / dict]
# Return a dict word -> count, case-insensitive.
# "the cat the dog" -> {"the":2, "cat":1, "dog":1}
from collections import Counter
def word_freq(s):
    count = Counter(s.lower().split())
    return dict(count)
print(word_freq("the cat the dog"))# -> {"the":2,"cat":1,"dog":1}

{'the': 2, 'cat': 1, 'dog': 1}

In [92]:
# 2. Anagram Check  [fundamentals / string]
# True if a and b are anagrams, case-insensitive, ignoring spaces.
# "Dormitory", "Dirty Room" -> True
def is_anagram(a, b):
    a = "".join([i for i in a.lower() if i.isalnum()])
    b = "".join([i for i in b.lower() if i.isalnum()])
    return sorted(a) == sorted(b)
print(is_anagram("Dormitory","Dirty Room"))# -> True ; 
print(is_anagram("abc","abd"))# -> False

True
False

In [79]:
# 3. Group Anagrams  [DSA / dict]
# Group words that are anagrams. Return a list of groups (each a list),
# groups in first-appearance order.
# ["eat","tea","tan","ate","nat"] -> [["eat","tea","ate"],["tan","nat"]]
from collections import defaultdict
def group_anagrams(words):
    grouped = defaultdict(list)
    for i in words:
        grouped["".join(sorted(i))].append(i)
    return list(grouped.values())
print(group_anagrams(["eat","tea","tan","ate","nat"]))# -> [["eat","tea","ate"],["tan","nat"]]

[['eat', 'tea', 'ate'], ['tan', 'nat']]

In [83]:
# 4. Valid Parentheses  [DSA / stack]
# True if (), [], {} are correctly matched and nested.
# "{[()]}" -> True ; "{[(])}" -> False
def balanced(s):
    brackets = {"}":"{","]":"[",")":"("}
    stack=[]
    for i in s:
        if i in brackets.values():
            stack.append(i)
        elif i in brackets:
            if not stack or stack[-1] != brackets[i]:
                return False
            stack.pop()
    return len(stack) == 0

print(balanced("{[()]}"))# -> True ; 
print(balanced("{[(])}"))# -> False ; 
print(balanced(""))# -> True

True
False
True

In [84]:
# 5. Min-Max Normalize  [numpy]
# Scale a 1D array to 0-1: (x - min) / (max - min).
import numpy as np
a = np.array([10, 20, 30, 40, 50])
(a-a.min())/(a.max() - a.min())

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [85]:
# 6. Euclidean Distance  [numpy]
# Return sqrt(sum((x - y)^2)) between two vectors.
import numpy as np
x = np.array([1.0, 2.0, 3.0])
y = np.array([4.0, 6.0, 3.0])
np.sqrt(sum((x-y)**2))

np.float64(5.0)

In [87]:
# 7. Fill Missing by Group  [pandas]
# Fill NaN in "score" with the mean of that row's own "team". Return the df.
import pandas as pd, numpy as np
df = pd.DataFrame({"team":["A","A","B","B"], "score":[10.0, np.nan, 20.0, np.nan]})
df['score'] = df['score'].fillna(df.groupby('team')['score'].transform('mean'))
df

  team  score
0    A   10.0
1    A   10.0
2    B   20.0
3    B   20.0

In [89]:
# 8. Top 2 Per Group  [pandas]
# For each dept, return the 2 highest-paid rows. Columns name, dept, salary.
import pandas as pd
emp = pd.DataFrame({
    "name":["A","B","C","D","E"], "dept":["IT","IT","IT","HR","HR"],
    "salary":[70000,90000,60000,50000,80000],
})
emp.sort_values('salary',ascending=False).groupby('dept',as_index=False).head(2)

  name dept  salary
1    B   IT   90000
4    E   HR   80000
0    A   IT   70000
3    D   HR   50000

In [90]:
# 9. Group, Filter, Sort  [pandas]
# Total amount per region, keep only totals >= 100, sorted descending,
# as a DataFrame (reset index), columns "region" and "total".
import pandas as pd
sales = pd.DataFrame({"region":["N","S","N","E","S","N"], "amount":[60,40,80,200,70,30]})
grouped = sales.groupby('region',as_index=False).agg(total = ('amount','sum'))
grouped[grouped['total']>=100].sort_values('total',ascending=False).reset_index(drop='index')

  region  total
0      E    200
1      N    170
2      S    110

In [97]:
# 1. Longest Consecutive Run  [Service / string]
# Return the length of the longest run of the SAME character appearing
# consecutively. Case-sensitive.
def longest_run(s):
    if s == "":
        return 0
    count = 1
    lst = []
    for i in range(1,len(s)):
        if s[i] == s[i-1]:
            count+=1
        else:
            lst.append(count)
            count=1
    return max(lst)
print(longest_run("aabbbbcaa"))# -> 4
print(longest_run("abcabcabc"))# -> 1     <- 'a' appears 3x but never in a row
print(longest_run(""))# -> 0

4
1
0

In [107]:
# 2. First Non-Repeating Character, case-insensitive  [AI screen / string]
# Return the first character that appears exactly once, treating upper and
# lower case as the same character. Return it as it first appeared.
def first_unique(s):
    for i in s:
        m=s.lower()
        if m.count(i.lower()) == 1:
            return i
    return None
print(first_unique("sTreSS"))# -> "T"     <- s/S repeats, T is alone
print(first_unique("aAbB"))# -> None      <- every letter repeats across case
# test: first_unique("xyzx") -> "y"

T
None

In [104]:
set('sTreSS')

{'S', 'T', 'e', 'r', 's'}