In [4]:
import pandas as pd

# ==========================================================
# Problem 1: Department Salary Report
#
# Business Requirement:
#
# Find the average salary of employees
# in each department.
#
# Expected Output:
# Department | Average Salary
# ==========================================================

df = pd.DataFrame({
    "Employee":["Alice","Bob","Charlie","David","Eva","Frank"],
    "Department":["HR","IT","IT","HR","Finance","Finance"],
    "Salary":[50000,70000,80000,55000,90000,85000]
})

df.groupby('Department').agg(Average_Salary=('Salary', 'mean'))

            Average_Salary
Department
Finance            87500.0
HR                 52500.0
IT                 75000.0

In [2]:
import pandas as pd

# ==========================================================
# Problem 2: Store Sales Analysis
#
# Business Requirement:
#
# Calculate the total sales generated
# by each store.
#
# Sort the result in descending order
# of total sales.
# ==========================================================

df = pd.DataFrame({
    "Store":["A","A","B","B","C","C","A","C"],
    "Sales":[120,80,150,130,90,110,100,95]
})

df.groupby('Store').sum().sort_values(by='Sales', ascending=False)

       Sales
Store
A        300
C        295
B        280

In [3]:
import pandas as pd

# ==========================================================
# Problem 3: Student Performance
#
# Business Requirement:
#
# Find the average marks obtained
# in each subject.
#
# Also display the highest marks
# in each subject.
# ==========================================================

df = pd.DataFrame({
    "Student":["A","B","C","D","E","F","G","H"],
    "Subject":["Math","Math","Science","Science",
               "English","English","Math","Science"],
    "Marks":[88,92,75,84,90,86,95,81]
})

df.groupby('Subject').agg(
    Average_mark=('Marks','mean'),
    Highest_mark=('Marks','max')
)

         Average_mark  Highest_mark
Subject
English     88.000000            90
Math        91.666667            95
Science     80.000000            84

In [5]:
import pandas as pd

# ==========================================================
# Problem 4: Company Employee Analytics
#
# Business Requirement:
#
# For each department,
# calculate:
#
# • Average Salary
# • Maximum Salary
# • Minimum Salary
# • Number of Employees
#
# Rename the output columns to:
#
# Average Salary
# Highest Salary
# Lowest Salary
# Employee Count
# ==========================================================

df = pd.DataFrame({
    "Department":["IT","IT","HR","HR",
                  "Finance","Finance","Marketing"],
    "Employee":["John","Alice","Bob","Sara",
                "Mike","Eva","Tom"],
    "Salary":[70000,85000,55000,60000,
              90000,95000,65000]
})

df.groupby('Department').agg(
    Average_salary=('Salary','mean'),
    Maximum_Salary=('Salary','max'),
    Minimum_Salary=('Salary','min'),
    Number_of_employees = ('Employee','count')
).rename(columns={'Average_salary':"Average Salary",
                  "Maximum_Salary":"Highest Salary",
                  "Minimum_Salary":"Lowest Salary",
                  "Number_of_employees":"Employee Count"})

            Average Salary  Highest Salary  Lowest Salary  Employee Count
Department
Finance            92500.0           95000          90000               2
HR                 57500.0           60000          55000               2
IT                 77500.0           85000          70000               2
Marketing          65000.0           65000          65000               1

In [11]:
import pandas as pd

# ==========================================================
# Problem 5: E-commerce Order Analytics
#
# Business Requirement:
#
# For each product category,
# calculate:
#
# • Total Revenue
# • Average Revenue
# • Highest Revenue
# • Lowest Revenue
# • Number of Orders
#
# Sort the output by
# Total Revenue (descending).
# ==========================================================

df = pd.DataFrame({
    "Category":["Electronics","Electronics","Furniture",
                "Furniture","Clothing","Clothing",
                "Electronics","Furniture"],
    "Revenue":[250000,300000,180000,
               220000,90000,120000,
               280000,240000]
})

df.groupby("Category").agg(**{"Total Revenue":('Revenue','sum'),
                              "Average Revenue":('Revenue','mean'),
                              "Highest Revenue":('Revenue','max'),
                             "Lowest Revenue":('Revenue','min'),
                             "Number of Orders":('Category','size')}).sort_values(by='Total Revenue',ascending=False)

,Total Revenue,Average Revenue,Highest Revenue,Lowest Revenue,Number of Orders
Category,,,,,
Electronics,830000,276666.666667,300000,250000,3
Furniture,640000,213333.333333,240000,180000,3
Clothing,210000,105000.000000,120000,90000,2

In [15]:
import pandas as pd

# ==========================================================
# Problem 1: Employee Salary Report
#
# Business Requirement:
#
# Find the average salary for each
# Department and Gender combination.
#
# Example:
#
# IT  M
# IT  F
# HR  M
# HR  F
#
# ==========================================================

df = pd.DataFrame({
    "Department":["IT","IT","IT","HR","HR","Finance","Finance","IT"],
    "Gender":["M","F","M","F","M","F","M","F"],
    "Salary":[70000,75000,82000,50000,62000,90000,85000,78000]
})

df.groupby(['Department','Gender']).agg(Average_Salary=('Salary','mean'))

                   Average_Salary
Department Gender
Finance    F              90000.0
           M              85000.0
HR         F              50000.0
           M              62000.0
IT         F              76500.0
           M              76000.0

In [16]:
import pandas as pd

# ==========================================================
# Problem 2: Department Average Salary
#
# Business Requirement:
#
# Add a new column named
#
# Department_Average
#
# containing the average salary of
# that employee's department.
#
# Example
#
# Alice  IT 70000  76250
# Bob    IT 82000  76250
#
# ==========================================================

df = pd.DataFrame({
    "Employee":["Alice","Bob","Charlie","David","Eva","Frank"],
    "Department":["IT","IT","IT","HR","HR","Finance"],
    "Salary":[70000,82000,77000,50000,60000,90000]
})

df['Department_Average'] = df.groupby('Department')['Salary'].transform('mean')
df

  Employee Department  Salary  Department_Average
0    Alice         IT   70000        76333.333333
1      Bob         IT   82000        76333.333333
2  Charlie         IT   77000        76333.333333
3    David         HR   50000        55000.000000
4      Eva         HR   60000        55000.000000
5    Frank    Finance   90000        90000.000000

In [18]:
df['Department_Range'] = df.groupby('Department')['Salary'].transform(lambda x: x.max() - x.min())
df

  Employee Department  Salary  Department_Average  Department_Range
0    Alice         IT   70000        76333.333333             12000
1      Bob         IT   82000        76333.333333             12000
2  Charlie         IT   77000        76333.333333             12000
3    David         HR   50000        55000.000000             10000
4      Eva         HR   60000        55000.000000             10000
5    Frank    Finance   90000        90000.000000                 0

In [20]:
import pandas as pd

# ==========================================================
# Problem 3: Highest Paid Employee
#
# Business Requirement:
#
# Return ONLY the highest paid employee
# from every department.
#
# Hint:
#
# Output should contain complete rows.
#
# ==========================================================

df = pd.DataFrame({
    "Employee":["Alice","Bob","Charlie","David","Eva","Frank","George"],
    "Department":["IT","IT","HR","HR","Finance","Finance","IT"],
    "Salary":[70000,90000,55000,62000,85000,95000,88000]
})

df.loc[df.groupby('Department')['Salary'].idxmax()]

  Employee Department  Salary
5    Frank    Finance   95000
3    David         HR   62000
1      Bob         IT   90000