In [13]:
import pandas as pd

orders = pd.DataFrame({
    "customer": ["A","A","B","C","B","A","C","D"],
    "amount": [100,200,150,300,250,50,100,500],
    "date": pd.to_datetime([
        "2025-01-01","2025-01-10","2025-01-02",
        "2025-01-05","2025-01-20","2025-02-01",
        "2025-02-05","2025-02-10"
    ])
})

# ==============================
# QUESTIONS
# ==============================
# 1. Find the total spending for each customer.
# 2. Find the average order value for each customer.
# 3. Find the customer who spent the most.
# 4. Find the first purchase date for every customer.
# 5. Sort customers by total spending in descending order.

# 1. Find the total spending for each customer.
total_speding_per_customer = orders.groupby('customer')['amount'].sum()
display(total_speding_per_customer)

# 2. Find the average order value for each customer.
average_speding_per_customer = orders.groupby('customer')['amount'].mean()
display(average_speding_per_customer)

# 3. Find the customer who spent the most.
print(f"The customer {orders.groupby('customer')['amount'].sum().idxmax()} has spent the most with the spend value of {orders.groupby('customer')['amount'].sum().max()}")

customer
A    350
B    400
C    400
D    500
Name: amount, dtype: int64

customer
A    116.666667
B    200.000000
C    200.000000
D    500.000000
Name: amount, dtype: float64

The customer D has spent the most with the spend value of 500

In [27]:
# 4. Find the first purchase date for every customer.
first_purchases = orders.groupby("customer")["date"].min().reset_index()
display(first_purchases)
# 5. Sort customers by total spending in descending order.
orders.groupby("customer")['amount'].sum().sort_values(ascending=False)

  customer       date
0        A 2025-01-01
1        B 2025-01-02
2        C 2025-01-05
3        D 2025-02-10

customer
D    500
B    400
C    400
A    350
Name: amount, dtype: int64

In [38]:
import pandas as pd

students = pd.DataFrame({
    "name": ["Alice", "Bob", "Charlie", "David", "Eva"],
    "age": [20, 22, 19, 21, 23],
    "marks": [85, 70, 95, 60, 88]
})

# ==============================
# QUESTIONS
# ==============================

# 1. Display only the "name" column.
# 2. Display the first 3 rows.
# 3. Display students with marks greater than 80.
# 4. Display students whose age is greater than 20.
# 5. Display only the "name" and "marks" columns.

# 1. Display only the "name" column.
display(students.name)

# 2. Display the first 3 rows.
display(students.head(3))

# 3. Display students with marks greater than 80.
display(students[students.marks > 80])

# 4. Display students whose age is greater than 20.
display(students[students.age > 20])

# 5. Display only the "name" and "marks" columns.
display(students[['name','marks']])

0      Alice
1        Bob
2    Charlie
3      David
4        Eva
Name: name, dtype: object

      name  age  marks
0    Alice   20     85
1      Bob   22     70
2  Charlie   19     95

      name  age  marks
0    Alice   20     85
2  Charlie   19     95
4      Eva   23     88

    name  age  marks
1    Bob   22     70
3  David   21     60
4    Eva   23     88

      name  marks
0    Alice     85
1      Bob     70
2  Charlie     95
3    David     60
4      Eva     88

In [45]:
import pandas as pd

employees = pd.DataFrame({
    "employee": ["A", "B", "C", "D"],
    "salary": [50000, 70000, 60000, 80000]
})

# ==============================
# QUESTIONS
# ==============================

# 1. Sort salaries in ascending order.
# 2. Sort salaries in descending order.
# 3. Create a new column "bonus" equal to 10% of salary.
# 4. Create a new column "total_salary".
# 5. Rename "employee" to "Employee_Name".

# 1. Sort salaries in ascending order.
display(employees.sort_values(by='salary',ascending=True))

# 2. Sort salaries in descending order.
display(employees.sort_values(by='salary',ascending=False))

# 3. Create a new column "bonus" equal to 10% of salary.
employees['bonus'] = employees['salary'] * 0.10
display(employees)

# 4. Create a new column "total_salary".
employees['total_salary'] = employees['salary'] + employees['bonus']
display(employees)

# 5. Rename "employee" to "Employee_Name".
employees = employees.rename(columns={'employee':'Employee_Name'})
display(employees)

  employee  salary
0        A   50000
2        C   60000
1        B   70000
3        D   80000

  employee  salary
3        D   80000
1        B   70000
2        C   60000
0        A   50000

  employee  salary   bonus
0        A   50000  5000.0
1        B   70000  7000.0
2        C   60000  6000.0
3        D   80000  8000.0

  employee  salary   bonus  total_salary
0        A   50000  5000.0       55000.0
1        B   70000  7000.0       77000.0
2        C   60000  6000.0       66000.0
3        D   80000  8000.0       88000.0

  Employee_Name  salary   bonus  total_salary
0             A   50000  5000.0       55000.0
1             B   70000  7000.0       77000.0
2             C   60000  6000.0       66000.0
3             D   80000  8000.0       88000.0

In [62]:
import pandas as pd
import numpy as np

df = pd.DataFrame({
    "name": ["Alice", "Bob", "Charlie", "David"],
    "age": [20, None, 25, None],
    "city": ["NY", None, "LA", "Chicago"]
})

# ==============================
# QUESTIONS
# ==============================

# 1. Count missing values.
# 2. Fill missing ages with the mean.
# 3. Fill missing city values with "Unknown".
# 4. Drop rows containing missing values.
# 5. Replace all missing values in the DataFrame with "N/A".

# 1. Count missing values.
display(df.isna().sum())

# 2. Fill missing ages with the mean.
df['age'].fillna(df['age'].mean(),inplace=True)
display(df)
# 3. Fill missing city values with "Unknown".
df['city'].fillna('Unknown',inplace=True)
display(df)
# 4. Drop rows containing missing values.
df = pd.DataFrame({
    "name": ["Alice", "Bob", "Charlie", "David"],
    "age": [20, None, 25, None],
    "city": ["NY", None, "LA", "Chicago"]
})
df.dropna(inplace=True)
display(df)
# 5. Replace all missing values in the DataFrame with "N/A".
df = pd.DataFrame({
    "name": ["Alice", "Bob", "Charlie", "David"],
    "age": [20, None, 25, None],
    "city": ["NY", None, "LA", "Chicago"]
})
df.fillna('N/A',inplace=True)
display(df)

name    0
age     2
city    1
dtype: int64

/var/folders/lv/p9vlph914d5554g_z5tcrsdm0000gn/T/ipykernel_26074/2617831465.py:24: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['age'].fillna(df['age'].mean(),inplace=True)

      name   age     city
0    Alice  20.0       NY
1      Bob  22.5     None
2  Charlie  25.0       LA
3    David  22.5  Chicago

/var/folders/lv/p9vlph914d5554g_z5tcrsdm0000gn/T/ipykernel_26074/2617831465.py:27: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['city'].fillna('Unknown',inplace=True)

      name   age     city
0    Alice  20.0       NY
1      Bob  22.5  Unknown
2  Charlie  25.0       LA
3    David  22.5  Chicago

      name   age city
0    Alice  20.0   NY
2  Charlie  25.0   LA

/var/folders/lv/p9vlph914d5554g_z5tcrsdm0000gn/T/ipykernel_26074/2617831465.py:43: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value 'N/A' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df.fillna('N/A',inplace=True)

      name   age     city
0    Alice  20.0       NY
1      Bob   N/A      N/A
2  Charlie  25.0       LA
3    David   N/A  Chicago

In [67]:
import pandas as pd

sales = pd.DataFrame({
    "city": ["Chennai", "Delhi", "Chennai", "Mumbai", "Delhi"],
    "sales": [100, 200, 150, 300, 250]
})

# ==============================
# QUESTIONS
# ==============================

# 1. Find total sales for each city.
# 2. Find average sales for each city.
# 3. Find maximum sales for each city.
# 4. Find minimum sales for each city.
# 5. Count the number of records for each city.

# 1. Find total sales for each city.
display(sales.groupby('city')['sales'].sum())

# 2. Find average sales for each city.
display(sales.groupby('city')['sales'].mean())

# 3. Find maximum sales for each city.
display(sales.groupby('city')['sales'].max())

# 4. Find minimum sales for each city.
display(sales.groupby('city')['sales'].min())

# 4. Find minimum sales for each city.
display(sales.groupby('city')['sales'].count())

city
Chennai    250
Delhi      450
Mumbai     300
Name: sales, dtype: int64

city
Chennai    125.0
Delhi      225.0
Mumbai     300.0
Name: sales, dtype: float64

city
Chennai    150
Delhi      250
Mumbai     300
Name: sales, dtype: int64

city
Chennai    100
Delhi      200
Mumbai     300
Name: sales, dtype: int64

city
Chennai    2
Delhi      2
Mumbai     1
Name: sales, dtype: int64

In [83]:
import pandas as pd

orders = pd.DataFrame({
    "customer": ["A", "A", "B", "B", "C"],
    "amount": [100, 200, 300, 150, 250]
})

# ==============================
# QUESTIONS
# ==============================

# 1. Find total amount spent by each customer.
# 2. Find average amount spent.
# 3. Find maximum purchase.
# 4. Find minimum purchase.
# 5. Use agg() to calculate sum, mean, max and min together.

# 1. Find total amount spent by each customer.
display(orders.groupby('customer').sum())

# 2. Find average amount spent.
display(orders.groupby('customer').mean())

# 3. Find maximum purchase.
display(orders.groupby('customer').max())

# 4. Find minimum purchase.
display(orders.groupby('customer').min())

# 5. Use agg() to calculate sum, mean, max and min together.
display(orders.groupby('customer').agg(total_amount=('amount','sum'),
                                      average_amount=('amount','mean'),
                                      maximum_purchase=('amount','max'),
                                      minimum_purchase=('amount','min')))

          amount
customer
A            300
B            450
C            250

          amount
customer
A          150.0
B          225.0
C          250.0

          amount
customer
A            200
B            300
C            250

          amount
customer
A            100
B            150
C            250

          total_amount  average_amount  maximum_purchase  minimum_purchase
customer
A                  300           150.0               200               100
B                  450           225.0               300               150
C                  250           250.0               250               250

In [89]:
import pandas as pd

customers = pd.DataFrame({
    "id": [1,2,3],
    "name": ["Alice","Bob","Charlie"]
})

orders = pd.DataFrame({
    "id": [1,2,2],
    "amount": [100,200,300]
})

# ==============================
# QUESTIONS
# ==============================

# 1. Perform an inner merge.
inner_merge = pd.merge(customers,orders,how='inner',on='id')
display(inner_merge)
# 2. Perform a left merge.
left_merge = pd.merge(customers,orders,how='left',on='id')
display(left_merge)
# 3. Perform a right merge.
right_merge = pd.merge(customers,orders,how='right',on='id')
display(right_merge)
# 4. Perform an outer merge.
outer_merge = pd.merge(customers,orders,how='outer',on='id')
display(outer_merge)
# 5. Find customers without orders.
merged = pd.merge(customers, orders, left_on='id', right_on='id', how='left')
no_orders = merged[merged['amount'].isna()][['id', 'name']]
display(no_orders)

   id   name  amount
0   1  Alice     100
1   2    Bob     200
2   2    Bob     300

   id     name  amount
0   1    Alice   100.0
1   2      Bob   200.0
2   2      Bob   300.0
3   3  Charlie     NaN

   id   name  amount
0   1  Alice     100
1   2    Bob     200
2   2    Bob     300

   id     name  amount
0   1    Alice   100.0
1   2      Bob   200.0
2   2      Bob   300.0
3   3  Charlie     NaN

   id     name
3   3  Charlie