In [4]:
import pandas as pd
import os

In [6]:
os.getcwd()

'/Users/mukundanramesh/projects/ai_ml_course_bootcamp_practice/ai-ml-course-bootcamp/Pandas'

In [81]:
df = pd.read_csv(r"datasets/Pandas - Q1 Sales.csv")

In [82]:
df.head(7)

     Country Region Sales Person    Date of Purchase    Total  Quantity
0      India  North         John  10/29/2018 0:00:00   100000       567
1         US  North         Bill   7/27/2011 0:00:00   120000      3000
2         UK  North       Thomas    7/6/2018 0:00:00   140000       345
3  Australia   East         John  12/16/2017 0:00:00   160000      1000
4     Africa   East         Bill   4/13/2017 0:00:00   180000       123
5  Singapore   East       Thomas   1/28/2012 0:00:00   200000      1000
6    Mylasia   West         John    2/2/2013 0:00:00  1000000      7890

In [49]:
df.tail(10)

      Country Region Sales Person    Date of Purchase   Total  Quantity
10  Australia  North         Bill  12/21/2018 0:00:00  120000       567
11     Africa  North       Thomas   9/19/2014 0:00:00  140000      1000
12  Singapore   East         John   5/23/2014 0:00:00  160000       892
13    Mylasia   East         Bill  10/31/2013 0:00:00  180000       444
14      India   East       Thomas  11/17/2016 0:00:00  200000        90
15         US   West         John   8/19/2017 0:00:00  220000        90
16         UK   West         Bill   11/8/2013 0:00:00  240000        90
17  Australia   West       Thomas    2/9/2011 0:00:00  260000        90
18     Africa  North         John    2/2/2017 0:00:00  140000        85
19  Singapore  North         Bill    7/1/2010 0:00:00  150000        85

In [20]:
print(df.describe())

              Total     Quantity
count  2.000000e+01    20.000000
mean   1.502500e+06   977.900000
std    5.769280e+06  1761.923497
min    1.000000e+05    85.000000
25%    1.400000e+05    90.000000
50%    1.700000e+05   505.500000
75%    2.250000e+05  1000.000000
max    2.600000e+07  7890.000000

In [22]:
df[['Country','Region']]

      Country Region
0       India  North
1          US  North
2          UK  North
3   Australia   East
4      Africa   East
5   Singapore   East
6     Mylasia   West
7       India   West
8          US   West
9          UK  North
10  Australia  North
11     Africa  North
12  Singapore   East
13    Mylasia   East
14      India   East
15         US   West
16         UK   West
17  Australia   West
18     Africa  North
19  Singapore  North

In [24]:
df.iloc[0:3]

  Country Region Sales Person    Date of Purchase   Total  Quantity
0   India  North         John  10/29/2018 0:00:00  100000       567
1      US  North         Bill   7/27/2011 0:00:00  120000      3000
2      UK  North       Thomas    7/6/2018 0:00:00  140000       345

In [27]:
df[(df["Country"] == "India") & (df["Quantity"] > 90)]

  Country Region Sales Person    Date of Purchase   Total  Quantity
0   India  North         John  10/29/2018 0:00:00  100000       567
7   India   West         Bill   7/11/2018 0:00:00  240000       200

In [29]:
call_made = [10] * 20

In [30]:
df["Call_made"] = call_made

In [31]:
df.head()

,Country,Region,Sales Person,Date of Purchase,Total,Quantity,Call_made
0,India,North,John,10/29/2018 0:00:00,100000,567,10
1,US,North,Bill,7/27/2011 0:00:00,120000,3000,10
2,UK,North,Thomas,7/6/2018 0:00:00,140000,345,10
3,Australia,East,John,12/16/2017 0:00:00,160000,1000,10
4,Africa,East,Bill,4/13/2017 0:00:00,180000,123,10

In [33]:
row = ['India','South','Jim','4/13/2018 0:00:00','160000','234','60']

In [35]:
new_row = pd.DataFrame([row],columns=df.columns.values)

In [38]:
sales_df = pd.concat([df, new_row], ignore_index=True)

In [39]:
df.tail(2)

,Country,Region,Sales Person,Date of Purchase,Total,Quantity,Call_made
19,Singapore,North,Bill,7/1/2010 0:00:00,150000,85,10
20,India,South,Jim,4/13/2018 0:00:00,160000,234,60

In [45]:
po_numbers = [int(f"1000{i}") for i in range(20)]
import random
random.shuffle(po_numbers)
po_numbers

[100015,
 100012,
 100016,
 100017,
 100011,
 100019,
 10002,
 10004,
 10006,
 10009,
 10003,
 10008,
 100014,
 10005,
 10007,
 100013,
 10001,
 10000,
 100010,
 100018]

In [52]:
df["PO_Numbers"] = po_numbers
df.set_index("PO_Numbers",inplace=True)
df.head()

,Country,Region,Sales Person,Date of Purchase,Total,Quantity
PO_Numbers,,,,,,
100015,India,North,John,10/29/2018 0:00:00,100000,567
100012,US,North,Bill,7/27/2011 0:00:00,120000,3000
100016,UK,North,Thomas,7/6/2018 0:00:00,140000,345
100017,Australia,East,John,12/16/2017 0:00:00,160000,1000
100011,Africa,East,Bill,4/13/2017 0:00:00,180000,123

In [58]:
df.sort_index(ascending=False)

,Country,Region,Sales Person,Date of Purchase,Total,Quantity
PO_Numbers,,,,,,
100019,Singapore,East,Thomas,1/28/2012 0:00:00,200000,1000
100018,Singapore,North,Bill,7/1/2010 0:00:00,150000,85
100017,Australia,East,John,12/16/2017 0:00:00,160000,1000
100016,UK,North,Thomas,7/6/2018 0:00:00,140000,345
100015,India,North,John,10/29/2018 0:00:00,100000,567
100014,Singapore,East,John,5/23/2014 0:00:00,160000,892
100013,US,West,John,8/19/2017 0:00:00,220000,90
100012,US,North,Bill,7/27/2011 0:00:00,120000,3000
100011,Africa,East,Bill,4/13/2017 0:00:00,180000,123
100010,Africa,North,John,2/2/2017 0:00:00,140000,85
10009,UK,North,John,9/29/2018 0:00:00,100000,1000
10008,Africa,North,Thomas,9/19/2014 0:00:00,140000,1000
10007,India,East,Thomas,11/17/2016 0:00:00,200000,90
10006,US,West,Thomas,3/9/2013 0:00:00,26000000,1000
10005,Mylasia,East,Bill,10/31/2013 0:00:00,180000,444
10004,India,West,Bill,7/11/2018 0:00:00,240000,200
10003,Australia,North,Bill,12/21/2018 0:00:00,120000,567
10002,Mylasia,West,John,2/2/2013 0:00:00,1000000,7890
10001,UK,West,Bill,11/8/2013 0:00:00,240000,90
10000,Australia,West,Thomas,2/9/2011 0:00:00,260000,90

In [62]:
df.sort_values(["Country","Region"],ascending=False, inplace=True)

In [63]:
df.head()

           Country Region Sales Person   Date of Purchase     Total  Quantity
PO_Numbers
10006           US   West       Thomas   3/9/2013 0:00:00  26000000      1000
100013          US   West         John  8/19/2017 0:00:00    220000        90
100012          US  North         Bill  7/27/2011 0:00:00    120000      3000
10001           UK   West         Bill  11/8/2013 0:00:00    240000        90
100016          UK  North       Thomas   7/6/2018 0:00:00    140000       345

### Date Time Handling

In [66]:
df["Date of Purchase"].iloc[0]

'3/9/2013 0:00:00'

In [67]:
type(df["Date of Purchase"].iloc[0])

str

In [70]:
pd.to_datetime(df["Date of Purchase"].iloc[0])

Timestamp('2013-03-09 00:00:00')

In [71]:
df["Date of Purchase"] = pd.to_datetime(df["Date of Purchase"])

In [75]:
df["Year"] = df["Date of Purchase"].dt.year

In [80]:
 df["Date of Purchase"].dt.minute

PO_Numbers
10006     0
100013    0
100012    0
10001     0
100016    0
10009     0
100018    0
100019    0
100014    0
10002     0
10005     0
10004     0
100015    0
10007     0
10000     0
10003     0
100017    0
10008     0
100010    0
100011    0
Name: Date of Purchase, dtype: int32

## Mathematical Functions

In [86]:
df[["Total","Quantity"]].max()

Total       26000000
Quantity        7890
dtype: int64

In [89]:
df.mean()

TypeError: Could not convert ['IndiaUSUKAustraliaAfricaSingaporeMylasiaIndiaUSUKAustraliaAfricaSingaporeMylasiaIndiaUSUKAustraliaAfricaSingapore'
 'NorthNorthNorthEastEastEastWestWestWestNorthNorthNorthEastEastEastWestWestWestNorthNorth'
 'JohnBillThomasJohnBillThomasJohnBillThomasJohnBillThomasJohnBillThomasJohnBillThomasJohnBill'
 '10/29/2018 0:00:007/27/2011 0:00:007/6/2018 0:00:0012/16/2017 0:00:004/13/2017 0:00:001/28/2012 0:00:002/2/2013 0:00:007/11/2018 0:00:003/9/2013 0:00:009/29/2018 0:00:0012/21/2018 0:00:009/19/2014 0:00:005/23/2014 0:00:0010/31/2013 0:00:0011/17/2016 0:00:008/19/2017 0:00:0011/8/2013 0:00:002/9/2011 0:00:002/2/2017 0:00:007/1/2010 0:00:00'] to numeric

In [90]:
df.mean(numeric_only=True)

Total       1502500.0
Quantity        977.9
dtype: float64

In [92]:
#1. Find the person who sold the least amount
df[["Sales Person","Total","Quantity"]][df["Total"] == df["Total"].min()]

  Sales Person     Total  Quantity
8       Thomas  26000000      1000

In [94]:
#2. Find the country with least quantity
df[["Country","Quantity"]][df["Quantity"] == df["Quantity"].min()]

      Country  Quantity
18     Africa        85
19  Singapore        85