In [1]:
import pandas as pd
import os

In [2]:
os.getcwd()

'/Users/mukundanramesh/projects/ai_ml_course_bootcamp_practice/ai-ml-course-bootcamp/Pandas'

In [3]:
df = pd.read_csv(r"datasets/Pandas - Q1 Sales.csv")

In [4]:
df.head(7)

     Country Region Sales Person    Date of Purchase    Total  Quantity
0      India  North         John  10/29/2018 0:00:00   100000       567
1         US  North         Bill   7/27/2011 0:00:00   120000      3000
2         UK  North       Thomas    7/6/2018 0:00:00   140000       345
3  Australia   East         John  12/16/2017 0:00:00   160000      1000
4     Africa   East         Bill   4/13/2017 0:00:00   180000       123
5  Singapore   East       Thomas   1/28/2012 0:00:00   200000      1000
6    Mylasia   West         John    2/2/2013 0:00:00  1000000      7890

In [5]:
df.tail(10)

      Country Region Sales Person    Date of Purchase   Total  Quantity
10  Australia  North         Bill  12/21/2018 0:00:00  120000       567
11     Africa  North       Thomas   9/19/2014 0:00:00  140000      1000
12  Singapore   East         John   5/23/2014 0:00:00  160000       892
13    Mylasia   East         Bill  10/31/2013 0:00:00  180000       444
14      India   East       Thomas  11/17/2016 0:00:00  200000        90
15         US   West         John   8/19/2017 0:00:00  220000        90
16         UK   West         Bill   11/8/2013 0:00:00  240000        90
17  Australia   West       Thomas    2/9/2011 0:00:00  260000        90
18     Africa  North         John    2/2/2017 0:00:00  140000        85
19  Singapore  North         Bill    7/1/2010 0:00:00  150000        85

In [6]:
print(df.describe())

              Total     Quantity
count  2.000000e+01    20.000000
mean   1.502500e+06   977.900000
std    5.769280e+06  1761.923497
min    1.000000e+05    85.000000
25%    1.400000e+05    90.000000
50%    1.700000e+05   505.500000
75%    2.250000e+05  1000.000000
max    2.600000e+07  7890.000000

In [7]:
df[['Country','Region']]

      Country Region
0       India  North
1          US  North
2          UK  North
3   Australia   East
4      Africa   East
5   Singapore   East
6     Mylasia   West
7       India   West
8          US   West
9          UK  North
10  Australia  North
11     Africa  North
12  Singapore   East
13    Mylasia   East
14      India   East
15         US   West
16         UK   West
17  Australia   West
18     Africa  North
19  Singapore  North

In [8]:
df.iloc[0:3]

  Country Region Sales Person    Date of Purchase   Total  Quantity
0   India  North         John  10/29/2018 0:00:00  100000       567
1      US  North         Bill   7/27/2011 0:00:00  120000      3000
2      UK  North       Thomas    7/6/2018 0:00:00  140000       345

In [9]:
df[(df["Country"] == "India") & (df["Quantity"] > 90)]

  Country Region Sales Person    Date of Purchase   Total  Quantity
0   India  North         John  10/29/2018 0:00:00  100000       567
7   India   West         Bill   7/11/2018 0:00:00  240000       200

In [10]:
call_made = [10] * 20

In [11]:
df["Call_made"] = call_made

In [12]:
df.head()

,Country,Region,Sales Person,Date of Purchase,Total,Quantity,Call_made
0,India,North,John,10/29/2018 0:00:00,100000,567,10
1,US,North,Bill,7/27/2011 0:00:00,120000,3000,10
2,UK,North,Thomas,7/6/2018 0:00:00,140000,345,10
3,Australia,East,John,12/16/2017 0:00:00,160000,1000,10
4,Africa,East,Bill,4/13/2017 0:00:00,180000,123,10

In [13]:
row = ['India','South','Jim','4/13/2018 0:00:00','160000','234','60']

In [14]:
new_row = pd.DataFrame([row],columns=df.columns.values)

In [15]:
sales_df = pd.concat([df, new_row], ignore_index=True)

In [16]:
df.tail(2)

,Country,Region,Sales Person,Date of Purchase,Total,Quantity,Call_made
18,Africa,North,John,2/2/2017 0:00:00,140000,85,10
19,Singapore,North,Bill,7/1/2010 0:00:00,150000,85,10

In [17]:
po_numbers = [int(f"1000{i}") for i in range(20)]
import random
random.shuffle(po_numbers)
po_numbers

[10006,
 10007,
 10004,
 100015,
 10001,
 100019,
 10005,
 10000,
 100011,
 10008,
 100012,
 100018,
 100010,
 100013,
 100014,
 100016,
 10003,
 100017,
 10002,
 10009]

In [18]:
df["PO_Numbers"] = po_numbers
df.set_index("PO_Numbers",inplace=True)
df.head()

,Country,Region,Sales Person,Date of Purchase,Total,Quantity,Call_made
PO_Numbers,,,,,,,
10006,India,North,John,10/29/2018 0:00:00,100000,567,10
10007,US,North,Bill,7/27/2011 0:00:00,120000,3000,10
10004,UK,North,Thomas,7/6/2018 0:00:00,140000,345,10
100015,Australia,East,John,12/16/2017 0:00:00,160000,1000,10
10001,Africa,East,Bill,4/13/2017 0:00:00,180000,123,10

In [19]:
df.sort_index(ascending=False)

,Country,Region,Sales Person,Date of Purchase,Total,Quantity,Call_made
PO_Numbers,,,,,,,
100019,Singapore,East,Thomas,1/28/2012 0:00:00,200000,1000,10
100018,Africa,North,Thomas,9/19/2014 0:00:00,140000,1000,10
100017,Australia,West,Thomas,2/9/2011 0:00:00,260000,90,10
100016,US,West,John,8/19/2017 0:00:00,220000,90,10
100015,Australia,East,John,12/16/2017 0:00:00,160000,1000,10
100014,India,East,Thomas,11/17/2016 0:00:00,200000,90,10
100013,Mylasia,East,Bill,10/31/2013 0:00:00,180000,444,10
100012,Australia,North,Bill,12/21/2018 0:00:00,120000,567,10
100011,US,West,Thomas,3/9/2013 0:00:00,26000000,1000,10
100010,Singapore,East,John,5/23/2014 0:00:00,160000,892,10
10009,Singapore,North,Bill,7/1/2010 0:00:00,150000,85,10
10008,UK,North,John,9/29/2018 0:00:00,100000,1000,10
10007,US,North,Bill,7/27/2011 0:00:00,120000,3000,10
10006,India,North,John,10/29/2018 0:00:00,100000,567,10
10005,Mylasia,West,John,2/2/2013 0:00:00,1000000,7890,10
10004,UK,North,Thomas,7/6/2018 0:00:00,140000,345,10
10003,UK,West,Bill,11/8/2013 0:00:00,240000,90,10
10002,Africa,North,John,2/2/2017 0:00:00,140000,85,10
10001,Africa,East,Bill,4/13/2017 0:00:00,180000,123,10
10000,India,West,Bill,7/11/2018 0:00:00,240000,200,10

In [20]:
df.sort_values(["Country","Region"],ascending=False, inplace=True)

In [21]:
df.head()

,Country,Region,Sales Person,Date of Purchase,Total,Quantity,Call_made
PO_Numbers,,,,,,,
100011,US,West,Thomas,3/9/2013 0:00:00,26000000,1000,10
100016,US,West,John,8/19/2017 0:00:00,220000,90,10
10007,US,North,Bill,7/27/2011 0:00:00,120000,3000,10
10003,UK,West,Bill,11/8/2013 0:00:00,240000,90,10
10004,UK,North,Thomas,7/6/2018 0:00:00,140000,345,10

### Date Time Handling

In [22]:
df["Date of Purchase"].iloc[0]

'3/9/2013 0:00:00'

In [23]:
type(df["Date of Purchase"].iloc[0])

str

In [24]:
pd.to_datetime(df["Date of Purchase"].iloc[0])

Timestamp('2013-03-09 00:00:00')

In [25]:
df["Date of Purchase"] = pd.to_datetime(df["Date of Purchase"])

In [26]:
df["Year"] = df["Date of Purchase"].dt.year

In [27]:
 df["Date of Purchase"].dt.minute

PO_Numbers
100011    0
100016    0
10007     0
10003     0
10004     0
10008     0
10009     0
100019    0
100010    0
10005     0
100013    0
10000     0
10006     0
100014    0
100017    0
100012    0
100015    0
100018    0
10002     0
10001     0
Name: Date of Purchase, dtype: int32

## Mathematical Functions

In [28]:
df[["Total","Quantity"]].max()

Total       26000000
Quantity        7890
dtype: int64

In [29]:
df.mean()

TypeError: Could not convert ['USUSUSUKUKUKSingaporeSingaporeSingaporeMylasiaMylasiaIndiaIndiaIndiaAustraliaAustraliaAustraliaAfricaAfricaAfrica'
 'WestWestNorthWestNorthNorthNorthEastEastWestEastWestNorthEastWestNorthEastNorthNorthEast'
 'ThomasJohnBillBillThomasJohnBillThomasJohnJohnBillBillJohnThomasThomasBillJohnThomasJohnBill'] to numeric

In [30]:
df.mean(numeric_only=True)

Total        1502500.0
Quantity         977.9
Call_made         10.0
Year            2014.9
dtype: float64

In [31]:
df["SellingRatio"] = df["Total"]/df["Quantity"]

In [32]:
df["Bonus"] = df["Total"] / 10

In [33]:
df.head()

,Country,Region,Sales Person,Date of Purchase,Total,Quantity,Call_made,Year,SellingRatio,Bonus
PO_Numbers,,,,,,,,,,
100011,US,West,Thomas,2013-03-09,26000000,1000,10,2013,26000.000000,2600000.0
100016,US,West,John,2017-08-19,220000,90,10,2017,2444.444444,22000.0
10007,US,North,Bill,2011-07-27,120000,3000,10,2011,40.000000,12000.0
10003,UK,West,Bill,2013-11-08,240000,90,10,2013,2666.666667,24000.0
10004,UK,North,Thomas,2018-07-06,140000,345,10,2018,405.797101,14000.0

In [34]:
#1. Find the person who sold the least amount
df[["Sales Person","Total","Quantity"]][df["SellingRatio"] == df["SellingRatio"].min()]

           Sales Person   Total  Quantity
PO_Numbers
10007              Bill  120000      3000

In [35]:
#2. Find the country with least quantity
df[["Country","Quantity"]][df["Quantity"] == df["Quantity"].min()]

              Country  Quantity
PO_Numbers
10009       Singapore        85
10002          Africa        85

In [36]:
df[["Total","Quantity"]].corr(numeric_only=True)

            Total  Quantity
Total     1.00000   0.03126
Quantity  0.03126   1.00000

### Indexes

In [41]:
# setting Header
df = pd.read_csv(r"datasets/Pandas - Q1 Sales.csv",header=4)
df.head()

   Australia  East    John 12/16/2017 0:00:00    160000  1000
0     Africa  East    Bill  4/13/2017 0:00:00    180000   123
1  Singapore  East  Thomas  1/28/2012 0:00:00    200000  1000
2    Mylasia  West    John   2/2/2013 0:00:00   1000000  7890
3      India  West    Bill  7/11/2018 0:00:00    240000   200
4         US  West  Thomas   3/9/2013 0:00:00  26000000  1000

In [47]:
# Setting Index
df = pd.read_csv(r"datasets/Pandas - Q1 Sales.csv")
df.set_index(keys = "Country",inplace=True)
df.loc["India"]

        Region Sales Person    Date of Purchase   Total  Quantity
Country
India    North         John  10/29/2018 0:00:00  100000       567
India     West         Bill   7/11/2018 0:00:00  240000       200
India     East       Thomas  11/17/2016 0:00:00  200000        90

In [48]:
df.reset_index(inplace=True)
df.head()

     Country Region Sales Person    Date of Purchase   Total  Quantity
0      India  North         John  10/29/2018 0:00:00  100000       567
1         US  North         Bill   7/27/2011 0:00:00  120000      3000
2         UK  North       Thomas    7/6/2018 0:00:00  140000       345
3  Australia   East         John  12/16/2017 0:00:00  160000      1000
4     Africa   East         Bill   4/13/2017 0:00:00  180000       123

In [49]:
df["Date of Purchase"] = pd.to_datetime(df["Date of Purchase"])

In [50]:
df.head()

     Country Region Sales Person Date of Purchase   Total  Quantity
0      India  North         John       2018-10-29  100000       567
1         US  North         Bill       2011-07-27  120000      3000
2         UK  North       Thomas       2018-07-06  140000       345
3  Australia   East         John       2017-12-16  160000      1000
4     Africa   East         Bill       2017-04-13  180000       123

### Grouping

In [54]:
df.groupby("Country").sum(numeric_only=True)

              Total  Quantity
Country
Africa       460000      1208
Australia    540000      1657
India        540000       857
Mylasia     1180000      8334
Singapore    510000      1977
UK           480000      1435
US         26340000      4090

In [55]:
df.groupby(["Country","Region"]).sum(numeric_only=True)

                     Total  Quantity
Country   Region
Africa    East      180000       123
          North     280000      1085
Australia East      160000      1000
          North     120000       567
          West      260000        90
India     East      200000        90
          North     100000       567
          West      240000       200
Mylasia   East      180000       444
          West     1000000      7890
Singapore East      360000      1892
          North     150000        85
UK        North     240000      1345
          West      240000        90
US        North     120000      3000
          West    26220000      1090