In [2]:
import pandas as pd

# Series

In [11]:
ds = pd.Series([1,2,3,4,5], index=[6,7,8,9,10])

In [17]:
ds.loc[6]

np.int64(1)

In [18]:
ds.iloc[0]

np.int64(1)

# Dataframe

In [44]:
students = {"Name":["Mukundan","Swathi","Shobhana"],
           "Age":[30,26,22],
           "CGPA": [7.2,8.8,9.2]
           }
df = pd.DataFrame(students,index=students["Name"])
df

              Name  Age  CGPA
Mukundan  Mukundan   30   7.2
Swathi      Swathi   26   8.8
Shobhana  Shobhana   22   9.2

In [46]:
students2 = {"Name":["Devi","Ramesh"],
           "Age":[55,60],
           "CGPA": [7.2,8.8,]
           }
pd.concat([df,pd.DataFrame(students2,index=students2["Name"])],axis = 0)

              Name  Age  CGPA
Mukundan  Mukundan   30   7.2
Swathi      Swathi   26   8.8
Shobhana  Shobhana   22   9.2
Devi          Devi   55   7.2
Ramesh      Ramesh   60   8.8

# Read CSV file

In [36]:
df = pd.read_csv(r'datasets/customers-100.csv')
df.head()

,Index,Customer Id,First Name,Last Name,Company,City,Country,Phone 1,Phone 2,Email,Subscription Date,Website
0,1,DD37Cf93aecA6Dc,Sheryl,Baxter,Rasmussen Group,East Leonard,Chile,229.077.5154,397.884.0519x718,zunigavanessa@smith.info,2020-08-24,http://www.stephenson.com/
1,2,1Ef7b82A4CAAD10,Preston,Lozano,Vega-Gentry,East Jimmychester,Djibouti,5153435776,686-620-1820x944,vmata@colon.com,2021-04-23,http://www.hobbs.com/
2,3,6F94879bDAfE5a6,Roy,Berry,Murillo-Perry,Isabelborough,Antigua and Barbuda,+1-539-402-0259,(496)978-3969x58947,beckycarr@hogan.com,2020-03-25,http://www.lawrence.com/
3,4,5Cef8BFA16c5e3c,Linda,Olsen,"Dominguez, Mcmillan and Donovan",Bensonview,Dominican Republic,001-808-617-6467x12895,+1-813-324-8756,stanleyblackwell@benson.org,2020-06-02,http://www.good-lyons.com/
4,5,053d585Ab6b3159,Joanna,Bender,"Martin, Lang and Andrade",West Priscilla,Slovakia (Slovak Republic),001-234-203-0635x76146,001-199-446-3860x3486,colinalvarado@miles.net,2021-04-17,https://goodwin-ingram.com/

In [65]:
df = df.reset_index(drop=True)  # reset first
df.set_index("Index", inplace=True)  # now set cleanly

In [66]:
df.head()

,Customer Id,First Name,Last Name,Company,City,Country,Phone 1,Phone 2,Email,Subscription Date,Website
Index,,,,,,,,,,,
1,DD37Cf93aecA6Dc,Sheryl,Baxter,Rasmussen Group,East Leonard,Chile,229.077.5154,397.884.0519x718,zunigavanessa@smith.info,2020-08-24,http://www.stephenson.com/
2,1Ef7b82A4CAAD10,Preston,Lozano,Vega-Gentry,East Jimmychester,Djibouti,5153435776,686-620-1820x944,vmata@colon.com,2021-04-23,http://www.hobbs.com/
3,6F94879bDAfE5a6,Roy,Berry,Murillo-Perry,Isabelborough,Antigua and Barbuda,+1-539-402-0259,(496)978-3969x58947,beckycarr@hogan.com,2020-03-25,http://www.lawrence.com/
4,5Cef8BFA16c5e3c,Linda,Olsen,"Dominguez, Mcmillan and Donovan",Bensonview,Dominican Republic,001-808-617-6467x12895,+1-813-324-8756,stanleyblackwell@benson.org,2020-06-02,http://www.good-lyons.com/
5,053d585Ab6b3159,Joanna,Bender,"Martin, Lang and Andrade",West Priscilla,Slovakia (Slovak Republic),001-234-203-0635x76146,001-199-446-3860x3486,colinalvarado@miles.net,2021-04-17,https://goodwin-ingram.com/

# Selection

In [71]:
# select specific columns
df["City"]

Index
1           East Leonard
2      East Jimmychester
3          Isabelborough
4             Bensonview
5         West Priscilla
             ...
96          East Richard
97          New Bradview
98            Ortegaland
99       Lake Elijahview
100            Judymouth
Name: City, Length: 100, dtype: object

In [73]:
# Mulitple Columns:
df[["Customer Id","First Name","Last Name","City"]]

           Customer Id First Name Last Name               City
Index
1      DD37Cf93aecA6Dc     Sheryl    Baxter       East Leonard
2      1Ef7b82A4CAAD10    Preston    Lozano  East Jimmychester
3      6F94879bDAfE5a6        Roy     Berry      Isabelborough
4      5Cef8BFA16c5e3c      Linda     Olsen         Bensonview
5      053d585Ab6b3159     Joanna    Bender     West Priscilla
...                ...        ...       ...                ...
96     cb8E23e48d22Eae       Karl     Greer       East Richard
97     CeD220bdAaCfaDf       Lynn  Atkinson       New Bradview
98     28CDbC0dFe4b1Db       Fred    Guerra         Ortegaland
99     c23d1D9EE8DEB0A     Yvonne    Farmer    Lake Elijahview
100    2354a0E336A91A1   Clarence    Haynes          Judymouth

[100 rows x 4 columns]

# Row Selection

In [76]:
df.iloc[2]

Customer Id                   6F94879bDAfE5a6
First Name                                Roy
Last Name                               Berry
Company                         Murillo-Perry
City                            Isabelborough
Country                   Antigua and Barbuda
Phone 1                       +1-539-402-0259
Phone 2                   (496)978-3969x58947
Email                     beckycarr@hogan.com
Subscription Date                  2020-03-25
Website              http://www.lawrence.com/
Name: 3, dtype: object

In [77]:
df = df.reset_index(drop=True)  # reset first
df.set_index("Customer Id", inplace=True)  # now set cleanly

In [78]:
df.head()

,First Name,Last Name,Company,City,Country,Phone 1,Phone 2,Email,Subscription Date,Website
Customer Id,,,,,,,,,,
DD37Cf93aecA6Dc,Sheryl,Baxter,Rasmussen Group,East Leonard,Chile,229.077.5154,397.884.0519x718,zunigavanessa@smith.info,2020-08-24,http://www.stephenson.com/
1Ef7b82A4CAAD10,Preston,Lozano,Vega-Gentry,East Jimmychester,Djibouti,5153435776,686-620-1820x944,vmata@colon.com,2021-04-23,http://www.hobbs.com/
6F94879bDAfE5a6,Roy,Berry,Murillo-Perry,Isabelborough,Antigua and Barbuda,+1-539-402-0259,(496)978-3969x58947,beckycarr@hogan.com,2020-03-25,http://www.lawrence.com/
5Cef8BFA16c5e3c,Linda,Olsen,"Dominguez, Mcmillan and Donovan",Bensonview,Dominican Republic,001-808-617-6467x12895,+1-813-324-8756,stanleyblackwell@benson.org,2020-06-02,http://www.good-lyons.com/
053d585Ab6b3159,Joanna,Bender,"Martin, Lang and Andrade",West Priscilla,Slovakia (Slovak Republic),001-234-203-0635x76146,001-199-446-3860x3486,colinalvarado@miles.net,2021-04-17,https://goodwin-ingram.com/

In [87]:
df.loc["1Ef7b82A4CAAD10":"053d585Ab6b3159",["First Name","Last Name","City"]]

                First Name Last Name               City
Customer Id
1Ef7b82A4CAAD10    Preston    Lozano  East Jimmychester
6F94879bDAfE5a6        Roy     Berry      Isabelborough
5Cef8BFA16c5e3c      Linda     Olsen         Bensonview
053d585Ab6b3159     Joanna    Bender     West Priscilla

In [95]:
df.iloc[56]

First Name                           Phyllis
Last Name                          Maldonado
Company                            Costa PLC
City                            Lake Whitney
Country                     Saint Barthelemy
Phone 1                           4500370767
Phone 2                 001-508-064-6725x017
Email                yhanson@warner-diaz.org
Subscription Date                 2021-01-25
Website              http://www.bernard.com/
Name: c8FE57cBBdCDcb2, dtype: object

In [91]:
df.iloc[0:5:2,0:3:2]

                First Name                   Company
Customer Id
DD37Cf93aecA6Dc     Sheryl           Rasmussen Group
6F94879bDAfE5a6        Roy             Murillo-Perry
053d585Ab6b3159     Joanna  Martin, Lang and Andrade

# Filtering

In [38]:
df = pd.read_json(r'datasets/iris.json')
df.head()

   sepalLength  sepalWidth  petalLength  petalWidth species
0          5.1         3.5          1.4         0.2  setosa
1          4.9         3.0          1.4         0.2  setosa
2          4.7         3.2          1.3         0.2  setosa
3          4.6         3.1          1.5         0.2  setosa
4          5.0         3.6          1.4         0.2  setosa

In [103]:
filtered = df[df["sepalLength"]> 5.0]
filtered.head()

    sepalLength  sepalWidth  petalLength  petalWidth species
0           5.1         3.5          1.4         0.2  setosa
5           5.4         3.9          1.7         0.4  setosa
10          5.4         3.7          1.5         0.2  setosa
14          5.8         4.0          1.2         0.2  setosa
15          5.7         4.4          1.5         0.4  setosa

In [105]:
df[df["species"] == "setosa"].head()

   sepalLength  sepalWidth  petalLength  petalWidth species
0          5.1         3.5          1.4         0.2  setosa
1          4.9         3.0          1.4         0.2  setosa
2          4.7         3.2          1.3         0.2  setosa
3          4.6         3.1          1.5         0.2  setosa
4          5.0         3.6          1.4         0.2  setosa

# Aggregation

In [106]:
df.min(numeric_only=True)

sepalLength    4.3
sepalWidth     2.0
petalLength    1.0
petalWidth     0.1
dtype: float64

In [107]:
df.max(numeric_only=True)

sepalLength    7.9
sepalWidth     4.4
petalLength    6.9
petalWidth     2.5
dtype: float64

In [108]:
df.sum(numeric_only=True)

sepalLength    876.5
sepalWidth     458.6
petalLength    563.7
petalWidth     179.9
dtype: float64

In [110]:
df.count()

sepalLength    150
sepalWidth     150
petalLength    150
petalWidth     150
species        150
dtype: int64

In [111]:
df.mean(numeric_only=True)

sepalLength    5.843333
sepalWidth     3.057333
petalLength    3.758000
petalWidth     1.199333
dtype: float64

In [114]:
df.groupby("species")["petalLength"].mean()

species
setosa        1.462
versicolor    4.260
virginica     5.552
Name: petalLength, dtype: float64

In [4]:
df["petalLengthtimes4"]  = df["petalLength"] * 4
df.head()

   sepalLength  sepalWidth  petalLength  petalWidth species  petalLengthtimes4
0          5.1         3.5          1.4         0.2  setosa                5.6
1          4.9         3.0          1.4         0.2  setosa                5.6
2          4.7         3.2          1.3         0.2  setosa                5.2
3          4.6         3.1          1.5         0.2  setosa                6.0
4          5.0         3.6          1.4         0.2  setosa                5.6

In [5]:
df = df.drop(columns=["petalLengthtimes4"])
df.head()

   sepalLength  sepalWidth  petalLength  petalWidth species
0          5.1         3.5          1.4         0.2  setosa
1          4.9         3.0          1.4         0.2  setosa
2          4.7         3.2          1.3         0.2  setosa
3          4.6         3.1          1.5         0.2  setosa
4          5.0         3.6          1.4         0.2  setosa

In [6]:
import numpy as np
df["petalLengthtimes"]  = np.nan
df.head()

   sepalLength  sepalWidth  petalLength  petalWidth species  petalLengthtimes
0          5.1         3.5          1.4         0.2  setosa               NaN
1          4.9         3.0          1.4         0.2  setosa               NaN
2          4.7         3.2          1.3         0.2  setosa               NaN
3          4.6         3.1          1.5         0.2  setosa               NaN
4          5.0         3.6          1.4         0.2  setosa               NaN

In [14]:
df["sepalWidth"].iloc[3] = np.nan

/var/folders/lv/p9vlph914d5554g_z5tcrsdm0000gn/T/ipykernel_30126/1671205735.py:1: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  df["sepalWidth"].iloc[3] = np.nan
/var/folders/lv/p9vlph914d5554g_z5tcrsdm0000gn/T/ipykernel_30126/1671205735.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["sepalWidth"].iloc[3] = np.nan

In [16]:
df= df.dropna(subset=["sepalWidth"])
df

     sepalLength  sepalWidth  petalLength  petalWidth    species
0            5.1         3.5          1.4         0.2     setosa
1            4.9         3.0          1.4         0.2     setosa
2            4.7         3.2          1.3         0.2     setosa
4            5.0         3.6          1.4         0.2     setosa
5            5.4         3.9          1.7         0.4     setosa
..           ...         ...          ...         ...        ...
145          6.7         3.0          5.2         2.3  virginica
146          6.3         2.5          5.0         1.9  virginica
147          6.5         3.0          5.2         2.0  virginica
148          6.2         3.4          5.4         2.3  virginica
149          5.9         3.0          5.1         1.8  virginica

[149 rows x 5 columns]

In [18]:
import numpy as np
df["petalLengthtimes"]  = np.nan
df.head()

   sepalLength  sepalWidth  petalLength  petalWidth species  petalLengthtimes
0          5.1         3.5          1.4         0.2  setosa               NaN
1          4.9         3.0          1.4         0.2  setosa               NaN
2          4.7         3.2          1.3         0.2  setosa               NaN
3          4.6         3.1          1.5         0.2  setosa               NaN
4          5.0         3.6          1.4         0.2  setosa               NaN

In [19]:
df = df.fillna({"petalLengthtimes":df["petalLength"]*4})
df.head()

   sepalLength  sepalWidth  petalLength  petalWidth species  petalLengthtimes
0          5.1         3.5          1.4         0.2  setosa               5.6
1          4.9         3.0          1.4         0.2  setosa               5.6
2          4.7         3.2          1.3         0.2  setosa               5.2
3          4.6         3.1          1.5         0.2  setosa               6.0
4          5.0         3.6          1.4         0.2  setosa               5.6

In [24]:
df["species"] = df["species"].replace({"S":"setosa","vir":"virginica"})
df.head()

   sepalLength  sepalWidth  petalLength  petalWidth species  petalLengthtimes
0          5.1         3.5          1.4         0.2  setosa               5.6
1          4.9         3.0          1.4         0.2  setosa               5.6
2          4.7         3.2          1.3         0.2  setosa               5.2
3          4.6         3.1          1.5         0.2  setosa               6.0
4          5.0         3.6          1.4         0.2  setosa               5.6

In [20]:
df["species"].unique

<bound method Series.unique of 0         setosa
1         setosa
2         setosa
3         setosa
4         setosa
         ...
145    virginica
146    virginica
147    virginica
148    virginica
149    virginica
Name: species, Length: 150, dtype: object>

In [26]:
df["species"] = df["species"].str.upper()
df.head()

   sepalLength  sepalWidth  petalLength  petalWidth species  petalLengthtimes
0          5.1         3.5          1.4         0.2  SETOSA               5.6
1          4.9         3.0          1.4         0.2  SETOSA               5.6
2          4.7         3.2          1.3         0.2  SETOSA               5.2
3          4.6         3.1          1.5         0.2  SETOSA               6.0
4          5.0         3.6          1.4         0.2  SETOSA               5.6

In [29]:
df["petalLength"] = df["petalLength"].astype(np.float64)
df.head()

   sepalLength  sepalWidth  petalLength  petalWidth species  petalLengthtimes
0          5.1         3.5          1.0         0.2  SETOSA               5.6
1          4.9         3.0          1.0         0.2  SETOSA               5.6
2          4.7         3.2          1.0         0.2  SETOSA               5.2
3          4.6         3.1          1.0         0.2  SETOSA               6.0
4          5.0         3.6          1.0         0.2  SETOSA               5.6

In [31]:
new_df = df.copy()

In [34]:
df = pd.concat((df,new_df),axis=0)
df

     sepalLength  sepalWidth  petalLength  petalWidth    species
0            5.1         3.5          1.4         0.2     setosa
1            4.9         3.0          1.4         0.2     setosa
2            4.7         3.2          1.3         0.2     setosa
3            4.6         3.1          1.5         0.2     setosa
4            5.0         3.6          1.4         0.2     setosa
..           ...         ...          ...         ...        ...
145          6.7         3.0          5.2         2.3  virginica
146          6.3         2.5          5.0         1.9  virginica
147          6.5         3.0          5.2         2.0  virginica
148          6.2         3.4          5.4         2.3  virginica
149          5.9         3.0          5.1         1.8  virginica

[300 rows x 5 columns]

In [35]:
df= df.drop_duplicates()
df

     sepalLength  sepalWidth  petalLength  petalWidth    species
0            5.1         3.5          1.4         0.2     setosa
1            4.9         3.0          1.4         0.2     setosa
2            4.7         3.2          1.3         0.2     setosa
3            4.6         3.1          1.5         0.2     setosa
4            5.0         3.6          1.4         0.2     setosa
..           ...         ...          ...         ...        ...
145          6.7         3.0          5.2         2.3  virginica
146          6.3         2.5          5.0         1.9  virginica
147          6.5         3.0          5.2         2.0  virginica
148          6.2         3.4          5.4         2.3  virginica
149          5.9         3.0          5.1         1.8  virginica

[149 rows x 5 columns]

In [39]:
df

     sepalLength  sepalWidth  petalLength  petalWidth    species
0            5.1         3.5          1.4         0.2     setosa
1            4.9         3.0          1.4         0.2     setosa
2            4.7         3.2          1.3         0.2     setosa
3            4.6         3.1          1.5         0.2     setosa
4            5.0         3.6          1.4         0.2     setosa
..           ...         ...          ...         ...        ...
145          6.7         3.0          5.2         2.3  virginica
146          6.3         2.5          5.0         1.9  virginica
147          6.5         3.0          5.2         2.0  virginica
148          6.2         3.4          5.4         2.3  virginica
149          5.9         3.0          5.1         1.8  virginica

[150 rows x 5 columns]