In [1]:
import pandas as pd

orders = pd.DataFrame({
    "customer": ["A","A","B","B","C","A","C","D"],
    "product": ["Laptop","Mouse","Laptop","Keyboard","Mouse","Keyboard","Laptop","Monitor"],
    "amount": [800,20,900,50,25,70,850,300]
})

# ==============================
# QUESTIONS
# ==============================

# 1. Find the total amount spent by each customer.
display(orders.groupby('customer')['amount'].sum())
# 2. Find the average purchase amount.
display(orders.groupby('customer')['amount'].mean())
# 3. Find the highest purchase amount.
display(orders.groupby('customer')['amount'].max())
# 4. Find the number of purchases.
display(orders.groupby('customer')['amount'].count())
# 5. Use agg() to calculate all the above in one statement.
display(orders.groupby('customer').agg(total_purchase_amount=('amount','sum'),
                                                 avg_purchase_amount=('amount','mean'),
                                                highest_purchase_amount=('amount','max'),
                                                 number_of_purchases=('amount','count')))

customer
A    890
B    950
C    875
D    300
Name: amount, dtype: int64

customer
A    296.666667
B    475.000000
C    437.500000
D    300.000000
Name: amount, dtype: float64

customer
A    800
B    900
C    850
D    300
Name: amount, dtype: int64

customer
A    3
B    2
C    2
D    1
Name: amount, dtype: int64

,total_purchase_amount,avg_purchase_amount,highest_purchase_amount,number_of_purchases
customer,,,,
A,890,296.666667,800,3
B,950,475.000000,900,2
C,875,437.500000,850,2
D,300,300.000000,300,1

In [2]:
import pandas as pd

sales = pd.DataFrame({
    "employee":["John","John","Alice","Alice","Bob","Bob"],
    "sales":[100,150,200,250,300,100]
})

# ==============================
# QUESTIONS
# ==============================

# Without reducing the number of rows:

# 1. Create a column containing total sales for each employee.
sales['total_sales_of_each_employee'] = sales.groupby('employee')['sales'].transform('sum')
# 2. Create a column containing average sales.
sales['avg_sales_of_each_employee'] = sales.groupby('employee')['sales'].transform('mean')
# 3. Create a column containing maximum sales.
sales['max_sales_of_each_employee'] = sales.groupby('employee')['sales'].transform('max')
# 4. Create a column containing transaction count.
sales['no_of_sales_of_each_employee'] = sales.groupby('employee')['sales'].transform('count')
# 5. Sort by total sales.
display(sales.sort_values(by="total_sales_of_each_employee",ascending=False))

,employee,sales,total_sales_of_each_employee,avg_sales_of_each_employee,max_sales_of_each_employee,no_of_sales_of_each_employee
2,Alice,200,450,225.0,250,2
3,Alice,250,450,225.0,250,2
4,Bob,300,400,200.0,300,2
5,Bob,100,400,200.0,300,2
0,John,100,250,125.0,150,2
1,John,150,250,125.0,150,2

In [3]:
import pandas as pd

employees = pd.DataFrame({
    "emp_id":[1,2,3,4],
    "name":["Alice","Bob","Charlie","David"],
    "dept_id":[10,20,30,20]
})

departments = pd.DataFrame({
    "dept_id":[10,20,30],
    "department":["IT","HR","Finance"]
})

# ==============================
# QUESTIONS
# ==============================

# 1. Perform an inner merge.
inner_merge = pd.merge(employees,departments,how='inner',on='dept_id')
display(inner_merge)
# 2. Perform a left merge.
left_merge = pd.merge(employees,departments,how='left',on='dept_id')
display(left_merge)
# 3. Perform an outer merge.
outer_merge = pd.merge(employees,departments,how='outer',on='dept_id')
display(outer_merge)
# 4. Display only employee name and department.
outer_merge = pd.merge(employees,departments,how='outer',on='dept_id')
display(outer_merge[['name','department']])
# 5. Rename the merged department column to dept_name.
outer_merge = pd.merge(employees,departments,how='outer',on='dept_id').rename(columns={'department':'dept_name'})
display(outer_merge)

   emp_id     name  dept_id department
0       1    Alice       10         IT
1       2      Bob       20         HR
2       3  Charlie       30    Finance
3       4    David       20         HR

   emp_id     name  dept_id department
0       1    Alice       10         IT
1       2      Bob       20         HR
2       3  Charlie       30    Finance
3       4    David       20         HR

   emp_id     name  dept_id department
0       1    Alice       10         IT
1       2      Bob       20         HR
2       4    David       20         HR
3       3  Charlie       30    Finance

      name department
0    Alice         IT
1      Bob         HR
2    David         HR
3  Charlie    Finance

   emp_id     name  dept_id dept_name
0       1    Alice       10        IT
1       2      Bob       20        HR
2       4    David       20        HR
3       3  Charlie       30   Finance

In [4]:
import pandas as pd

customers = pd.DataFrame({
    "name":[" alice ","BOB","Charlie","david","Ankit"],
    "city":["Chennai","Delhi","Mumbai","Delhi","Chennai"]
})

# ==============================
# QUESTIONS
# ==============================

# 1. Remove leading/trailing spaces.
customers['name'] = customers['name'].str.strip()
display(customers)
# 2. Convert names to title case.
customers['name'] = customers['name'].str.capitalize()
display(customers)
# 3. Find names containing the letter 'a'.
display(customers[customers['name'].str.contains('a')])
# 4. Find customers from Chennai.
display(customers[customers['city']=='Chennai'])
# 5. Sort names alphabetically.
display(customers.sort_values(by='name'))

      name     city
0    alice  Chennai
1      BOB    Delhi
2  Charlie   Mumbai
3    david    Delhi
4    Ankit  Chennai

      name     city
0    Alice  Chennai
1      Bob    Delhi
2  Charlie   Mumbai
3    David    Delhi
4    Ankit  Chennai

      name    city
2  Charlie  Mumbai
3    David   Delhi

    name     city
0  Alice  Chennai
4  Ankit  Chennai

      name     city
0    Alice  Chennai
4    Ankit  Chennai
1      Bob    Delhi
2  Charlie   Mumbai
3    David    Delhi

In [5]:
import pandas as pd

orders = pd.DataFrame({
    "order_date":pd.to_datetime([
        "2025-01-10",
        "2025-02-14",
        "2025-02-28",
        "2025-06-01",
        "2025-03-15"
    ])
})

# ==============================
# QUESTIONS
# ==============================
# 1. Extract year.
display(orders.order_date.dt.year)
# 2. Extract month.
display(orders.order_date.dt.month)
# 3. Extract weekday name.
display(orders.order_date.dt.day_name())
# 4. Extract quarter.
display(orders.order_date.dt.quarter)
# 5. Create a column containing day of year.
orders['Day']=orders.order_date.dt.day_name()
display(orders)

0    2025
1    2025
2    2025
3    2025
4    2025
Name: order_date, dtype: int32

0    1
1    2
2    2
3    6
4    3
Name: order_date, dtype: int32

0      Friday
1      Friday
2      Friday
3      Sunday
4    Saturday
Name: order_date, dtype: object

0    1
1    1
2    1
3    2
4    1
Name: order_date, dtype: int32

  order_date       Day
0 2025-01-10    Friday
1 2025-02-14    Friday
2 2025-02-28    Friday
3 2025-06-01    Sunday
4 2025-03-15  Saturday

In [6]:
import pandas as pd

sales = pd.DataFrame({
    "city":["Chennai","Delhi","Delhi","Mumbai","Chennai","Mumbai"],
    "product":["Laptop","Laptop","Phone","Phone","Phone","Laptop"],
    "sales":[100,150,120,180,160,200]
})

# ==============================
# QUESTIONS
# ==============================

# 1. Create a pivot table.
# 2. Show cities as rows.
# 3. Show products as columns.
# 4. Fill missing values with 0.
# 5. Add row and column totals.
pt = pd.pivot_table(sales,index='city',columns='product',values='sales',aggfunc='sum',margins=True,margins_name='Total')
pt

product  Laptop  Phone  Total
city
Chennai     100    160    260
Delhi       150    120    270
Mumbai      200    180    380
Total       450    460    910

In [7]:
import pandas as pd
import numpy as np

employees = pd.DataFrame({
    "name":["Alice","Bob","Charlie","David"],
    "age":[25,None,28,None],
    "salary":[50000,None,70000,60000],
    "city":["Chennai","Delhi",None,"Mumbai"]
})

# ==============================
# QUESTIONS
# ==============================

# 1. Count missing values.
display(employees.isna().sum())
# 2. Fill missing age using median.
employees['age'].fillna(employees['age'].mean(),inplace=True)
# 3. Fill missing city with "Unknown".
employees['city'].fillna('Unknown',inplace=True)
# 4. Drop rows where salary is missing.
employees = pd.DataFrame({
    "name":["Alice","Bob","Charlie","David"],
    "age":[25,None,28,None],
    "salary":[50000,None,70000,60000],
    "city":["Chennai","Delhi",None,"Mumbai"]
})
employees.dropna(inplace=True)
display(employees)
# 5. Replace all remaining NaN values with "Missing".
employees = pd.DataFrame({
    "name":["Alice","Bob","Charlie","David"],
    "age":[25,None,28,None],
    "salary":[50000,None,70000,60000],
    "city":["Chennai","Delhi",None,"Mumbai"]
})
employees.fillna('Missing',inplace=True)
employees

name      0
age       2
salary    1
city      1
dtype: int64

/var/folders/lv/p9vlph914d5554g_z5tcrsdm0000gn/T/ipykernel_3762/1385068457.py:18: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  employees['age'].fillna(employees['age'].mean(),inplace=True)
/var/folders/lv/p9vlph914d5554g_z5tcrsdm0000gn/T/ipykernel_3762/1385068457.py:20: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  employees['city'].fillna('Unknown',inplace=True)

    name   age   salary     city
0  Alice  25.0  50000.0  Chennai

/var/folders/lv/p9vlph914d5554g_z5tcrsdm0000gn/T/ipykernel_3762/1385068457.py:37: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value 'Missing' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  employees.fillna('Missing',inplace=True)

      name      age   salary     city
0    Alice     25.0  50000.0  Chennai
1      Bob  Missing  Missing    Delhi
2  Charlie     28.0  70000.0  Missing
3    David  Missing  60000.0   Mumbai

In [8]:
import pandas as pd

students = pd.DataFrame({
    "id":[1,2,2,3,4,4,4],
    "name":["Alice","Bob","Bob","Charlie","David","David","David"],
    "marks":[90,80,80,95,85,85,85]
})

# ==============================
# QUESTIONS
# ==============================

# 1. Find duplicate rows.
display(students[students.duplicated])
# 2. Count duplicate rows.
display(f"The number of duplicates is {students.duplicated().sum()}")
# 3. Remove duplicate rows.
students.drop_duplicates(inplace=True)
display(students)
# 4. Remove duplicates based only on "id".
students.drop_duplicates(subset=['id'],inplace=True)
display(students)
# 5. Keep only the last occurrence.
students.drop_duplicates(keep='last',inplace=True)
display(students)

   id   name  marks
2   2    Bob     80
5   4  David     85
6   4  David     85

'The number of duplicates is 3'

   id     name  marks
0   1    Alice     90
1   2      Bob     80
3   3  Charlie     95
4   4    David     85

   id     name  marks
0   1    Alice     90
1   2      Bob     80
3   3  Charlie     95
4   4    David     85

   id     name  marks
0   1    Alice     90
1   2      Bob     80
3   3  Charlie     95
4   4    David     85

In [9]:
import pandas as pd

employees = pd.DataFrame({
    "department":["IT","IT","HR","HR","Finance","Finance"],
    "employee":["A","B","C","D","E","F"],
    "salary":[80000,90000,50000,60000,70000,75000]
})

# ==============================
# QUESTIONS
# ==============================

# 1. Rank salaries within each department.
employees['rank'] = employees.groupby('department')['salary'].rank(method='dense')
display(employees)
# 2. Find the highest-paid employee in each department.
employees['rank'] = employees.groupby('department')['salary'].rank(method='dense')
display(employees)
# 3. Find the second highest-paid employee in each department.
display(employees[employees['rank'] == 2])
# 4. Sort by department and rank.
display(employees.sort_values(by=['department','rank']))
# 5. Display only rank 1 employees.
display(employees[employees['rank'] == 1])

  department employee  salary  rank
0         IT        A   80000   1.0
1         IT        B   90000   2.0
2         HR        C   50000   1.0
3         HR        D   60000   2.0
4    Finance        E   70000   1.0
5    Finance        F   75000   2.0

  department employee  salary  rank
0         IT        A   80000   1.0
1         IT        B   90000   2.0
2         HR        C   50000   1.0
3         HR        D   60000   2.0
4    Finance        E   70000   1.0
5    Finance        F   75000   2.0

  department employee  salary  rank
1         IT        B   90000   2.0
3         HR        D   60000   2.0
5    Finance        F   75000   2.0

  department employee  salary  rank
4    Finance        E   70000   1.0
5    Finance        F   75000   2.0
2         HR        C   50000   1.0
3         HR        D   60000   2.0
0         IT        A   80000   1.0
1         IT        B   90000   2.0

  department employee  salary  rank
0         IT        A   80000   1.0
2         HR        C   50000   1.0
4    Finance        E   70000   1.0

In [10]:
import pandas as pd

transactions = pd.DataFrame({
    "customer":["A","A","A","B","B","C","C","D"],
    "product":["Laptop","Mouse","Keyboard","Laptop","Mouse","Laptop","Monitor","Phone"],
    "amount":[800,20,50,900,25,850,300,700]
})

# ==============================
# QUESTIONS
# ==============================

# Without using loops:

# 1. Calculate total spending per customer.
display(transactions.groupby('customer')['amount'].sum())
# 2. Calculate average spending per customer.
display(transactions.groupby('customer')['amount'].mean())
# 3. Count purchases per customer.
display(transactions.groupby('customer')['amount'].count())
# 4. Create a column showing each customer's total spending.
transactions['Total_spends'] = transactions.groupby('customer')['amount'].transform('sum')
display(transactions)
# 5. Create a column showing the percentage contribution of each purchase
#    to that customer's total spending.
transactions['Pct_Of_Customer_Total'] = ((transactions['amount'] / transactions['Total_spends']) * 100).round(2)
display(transactions)
# 6. Sort customers by total spending.
transactions.sort_values(by='Total_spends',ascending=False)

customer
A     870
B     925
C    1150
D     700
Name: amount, dtype: int64

customer
A    290.0
B    462.5
C    575.0
D    700.0
Name: amount, dtype: float64

customer
A    3
B    2
C    2
D    1
Name: amount, dtype: int64

  customer   product  amount  Total_spends
0        A    Laptop     800           870
1        A     Mouse      20           870
2        A  Keyboard      50           870
3        B    Laptop     900           925
4        B     Mouse      25           925
5        C    Laptop     850          1150
6        C   Monitor     300          1150
7        D     Phone     700           700

  customer   product  amount  Total_spends  Pct_Of_Customer_Total
0        A    Laptop     800           870                  91.95
1        A     Mouse      20           870                   2.30
2        A  Keyboard      50           870                   5.75
3        B    Laptop     900           925                  97.30
4        B     Mouse      25           925                   2.70
5        C    Laptop     850          1150                  73.91
6        C   Monitor     300          1150                  26.09
7        D     Phone     700           700                 100.00

  customer   product  amount  Total_spends  Pct_Of_Customer_Total
5        C    Laptop     850          1150                  73.91
6        C   Monitor     300          1150                  26.09
3        B    Laptop     900           925                  97.30
4        B     Mouse      25           925                   2.70
0        A    Laptop     800           870                  91.95
1        A     Mouse      20           870                   2.30
2        A  Keyboard      50           870                   5.75
7        D     Phone     700           700                 100.00

In [11]:
# Create a new column called "salary_band"
# If salary > 80000 -> High
# Else -> Low

employees["salary_band"] = employees["salary"].apply(...)

TypeError: 'ellipsis' object is not callable

In [ ]:
import pandas as pd
df = pd.DataFrame({
    "maths": [80, 70, 90],
    "science": [90, 60, 85]
})

In [ ]:
df['maths']=df['maths'].apply(lambda x: x+5)
df