In [8]:
import pandas as pd

df = pd.DataFrame({
    "Employee": ["Alice", "Bob", "Charlie", "David", "Eva", "Frank"],
    "Department": ["HR", "IT", "IT", "HR", "Finance", "Finance"],
    "Salary": [50000, 70000, 80000, 55000, 90000, 85000]
})
"""
Task

Create a pivot table showing:

Department	Average Salary"""
pt1 = pd.pivot_table(df,index="Department",values='Salary',aggfunc='mean')
pt1

             Salary
Department
Finance     87500.0
HR          52500.0
IT          75000.0

In [10]:
df = pd.DataFrame({
    "Region": ["North","North","South","South","East","East"],
    "Product": ["Laptop","Phone","Laptop","Phone","Laptop","Phone"],
    "Sales": [100,80,120,90,150,110]
})
"""Task

Create a pivot table like

Region	Laptop	Phone
East	?	?
North	?	?
South	?	?

using the sum of sales."""
pt = pd.pivot_table(df,index='Region',columns='Product',values='Sales',aggfunc='sum')
pt

Product  Laptop  Phone
Region
East        150    110
North       100     80
South       120     90

In [16]:
#Exercise 3: Average Marks by Class and Subject (Medium)
df = pd.DataFrame({
    "Student":["A","B","C","D","E","F"],
    "Class":["10","10","10","9","9","9"],
    "Subject":["Math","Science","Math","Science","Math","Science"],
    "Marks":[88,75,92,81,95,78]
})
pt = pd.pivot_table(df,index='Class',columns='Subject',values='Marks',aggfunc='mean')
display(pt)

Subject  Math  Science
Class
10       90.0     75.0
9        95.0     79.5

In [30]:
#Exercise 4: Monthly Revenue Report (Medium)
df = pd.DataFrame({
    "Month":["Jan","Jan","Jan","Feb","Feb","Mar","Mar"],
    "Category":["Food","Electronics","Food","Food","Electronics","Food","Electronics"],
    "Revenue":[5000,12000,4000,6000,15000,7000,18000]
})
pt = pd.pivot_table(df,index='Month',columns='Category',values='Revenue',aggfunc='sum',fill_value=0)
display(pt)

Category  Electronics  Food
Month
Feb             15000  6000
Jan             12000  9000
Mar             18000  7000

In [25]:
#Exercise 5: Company Sales Dashboard (Medium)
df = pd.DataFrame({
    "Region":["North","North","North","South","South","East","East","East"],
    "Salesperson":["John","John","Mike","Mike","Sara","Sara","John","Mike"],
    "Product":["Laptop","Phone","Laptop","Phone","Laptop","Phone","Laptop","Phone"],
    "Sales":[100,150,120,170,200,180,110,140]
})
"""
Tasks
Part A

Create a pivot table showing

| Region | Total Sales |
"""
pt = pd.pivot_table(df,index='Region',values='Sales',aggfunc='sum')
pt = pt.rename(columns={'Sales':'Total Sales'})
pt

        Total Sales
Region
East            430
North           370
South           370

In [19]:
"""Part B

Create a pivot table

| Region | Laptop | Phone |

using sum."""
pt = pd.pivot_table(df,index='Region',columns='Product',values='Sales',aggfunc='sum')
pt

Product  Laptop  Phone
Region
East        110    320
North       220    150
South       200    170

In [20]:
"""Part C

Create a pivot table

| Salesperson | Average Sales |"""
pt = pd.pivot_table(df,index='Salesperson',values='Sales',aggfunc="mean")
pt

                  Sales
Salesperson
John         120.000000
Mike         143.333333
Sara         190.000000

In [24]:
"""Part D (Challenge)

Create a pivot table

| Region | Laptop Sales | Phone Sales | Grand Total |

using margins."""
pt = pd.pivot_table(df,index='Region',columns='Product',values='Sales',aggfunc="sum",margins=True, 
    margins_name='Grand Total')
pt = pt.rename(columns={
    'Laptop': 'Laptop Sales',
    'Phone': 'Phone Sales'
})
pt.columns.name = None
pt

             Laptop Sales  Phone Sales  Grand Total
Region
East                  110          320          430
North                 220          150          370
South                 200          170          370
Grand Total           530          640         1170

In [26]:
df = pd.DataFrame({
    "Department":["IT","IT","IT","HR","HR","Finance","Finance"],
    "Gender":["M","F","M","F","M","F","M"],
    "Experience":[2,4,5,3,6,7,5],
    "Salary":[60000,75000,80000,50000,65000,90000,85000]
})

Create a pivot table that shows:

Rows → Department
Columns → Gender
Values → Salary
Aggregation → Average salary

Then extend it to show both:

Average Salary
Maximum Salary

using a single pivot table.

In [27]:
pt = pd.pivot_table(df,index='Department',columns='Gender',values='Salary',aggfunc=["mean",'max'])
pt

               mean             max
Gender            F        M      F      M
Department
Finance     90000.0  85000.0  90000  85000
HR          50000.0  65000.0  50000  65000
IT          75000.0  70000.0  75000  80000

In [35]:
#Problem 1: Retail Store Sales Report ⭐ (Easy)
#Dataset
import pandas as pd

df = pd.DataFrame({
    "Store": ["A","A","A","B","B","B","C","C"],
    "Product": ["Laptop","Phone","Tablet","Laptop","Phone","Tablet","Laptop","Phone"],
    "Sales": [120000,50000,30000,90000,60000,25000,100000,55000]
})
"""Business Requirement

The regional manager wants to compare how much revenue each store generated from each product.

Expected Output

          Laptop   Phone   Tablet
Store
A
B
C"""

pt = pd.pivot_table(df,index='Store',columns='Product',values='Sales',aggfunc='sum',fill_value=0)
pt

Product  Laptop  Phone  Tablet
Store
A        120000  50000   30000
B         90000  60000   25000
C        100000  55000       0

In [37]:
#Problem 2: Employee Performance Dashboard ⭐⭐
#Dataset
df = pd.DataFrame({
    "Employee":["Alice","Bob","Alice","Bob","Charlie","Charlie","Alice","Bob"],
    "Quarter":["Q1","Q1","Q2","Q2","Q1","Q2","Q3","Q3"],
    "Sales":[25,18,30,22,28,35,40,32]
})
"""Business Requirement

The HR team wants to know the average quarterly sales made by each employee.

Design a report where each employee is a row and each quarter is a separate column."""
pt = pd.pivot_table(df,index='Employee',columns='Quarter',values='Sales',aggfunc='mean',fill_value=0)
pt

Quarter     Q1    Q2    Q3
Employee
Alice     25.0  30.0  40.0
Bob       18.0  22.0  32.0
Charlie   28.0  35.0   0.0

In [41]:
#Problem 3: Hospital Patient Analytics ⭐⭐⭐
#Dataset
df = pd.DataFrame({
    "Department":["Cardiology","Cardiology","Neurology","Neurology","Orthopedic","Orthopedic","Cardiology","Neurology"],
    "Gender":["Male","Female","Male","Female","Male","Female","Male","Female"],
    "Age":[62,58,45,50,38,41,70,55]
})
"""Business Requirement

The hospital administrator wants to compare the average age of patients by department and gender.

Bonus

Also display the oldest patient in every department-gender combination."""
pt = pd.pivot_table(df,index='Department',columns='Gender',values='Age',aggfunc=['mean','max'])
pt

             mean          max
Gender     Female  Male Female Male
Department
Cardiology   58.0  66.0     58   70
Neurology    52.5  45.0     55   45
Orthopedic   41.0  38.0     41   38

In [43]:
#Problem 4: E-commerce Analytics ⭐⭐⭐
#Dataset
df = pd.DataFrame({
    "Month":["Jan","Jan","Jan","Feb","Feb","Mar","Mar","Mar","Apr"],
    "Category":["Electronics","Furniture","Clothing",
                "Electronics","Furniture",
                "Electronics","Furniture","Clothing",
                "Electronics"],
    "Orders":[120,60,90,140,70,160,80,100,180]
})
"""Business Requirement

The CEO wants a dashboard showing the total number of orders placed for each product category every month.

Bonus

If a category has no orders in a month, show 0 instead of NaN."""
pt= pd.pivot_table(df,index='Month',columns='Category',values='Orders',aggfunc='sum',fill_value=0)
pt

Category  Clothing  Electronics  Furniture
Month
Apr              0          180          0
Feb              0          140         70
Jan             90          120         60
Mar            100          160         80

In [46]:
#Problem 5: Company Salary Analytics ⭐⭐⭐⭐ (Interview-Level)
#Dataset
df = pd.DataFrame({
    "Department":["IT","IT","IT","HR","HR","Finance","Finance","Finance","Marketing"],
    "Gender":["M","F","M","F","M","F","M","F","M"],
    "Salary":[70000,75000,82000,50000,62000,90000,87000,95000,65000],
    "Experience":[2,3,5,1,4,8,6,10,3]
})
"""Business Requirement

The HR Director asks you to prepare a salary dashboard with the following requirements:

Show the average salary for each department broken down by gender.
Also show the maximum salary.
Add a Grand Total row and column.
Replace missing values with 0.
Rename the grand total label to Overall."""
pt =pd.pivot_table(df,index="Department",columns="Gender",values='Salary',aggfunc=['mean','max'],margins=True,margins_name='Overall',fill_value=0)
pt

               mean                           max
Gender            F        M       Overall      F      M Overall
Department
Finance     92500.0  87000.0  90666.666667  95000  87000   95000
HR          50000.0  62000.0  56000.000000  50000  62000   62000
IT          75000.0  76000.0  75666.666667  75000  82000   82000
Marketing       0.0  65000.0  65000.000000      0  65000   65000
Overall     77500.0  73200.0  75111.111111  95000  87000   95000

In [50]:
#⭐⭐ Final Boss (Real Interview Scenario)
#Dataset
df = pd.DataFrame({
    "Region":["North","North","South","South","East","East","West","West"],
    "Product":["Laptop","Phone","Laptop","Phone","Laptop","Phone","Laptop","Phone"],
    "Year":[2024,2024,2024,2025,2025,2025,2024,2025],
    "Sales":[150,80,120,100,170,90,140,110]
})
"""Business Requirement

Your manager asks:

"I want one single pivot table that tells me everything."

Create a report that:

Shows each Region as rows.
Shows both Product and Year as column levels.
Displays the sum of Sales.
Includes Overall totals.
Replaces missing values with 0."""
pt= pd.pivot_table(df,index='Region',columns=['Product','Year'],values='Sales',aggfunc='sum',margins=True,fill_value=0,margins_name='Overall total')
pt

Product       Laptop      Phone      Overall total
Year            2024 2025  2024 2025
Region
East               0  170     0   90           260
North            150    0    80    0           230
South            120    0     0  100           220
West             140    0     0  110           250
Overall total    410  170    80  300           960

In [57]:
pd.merge(df,df,on='Region',how='left',suffixes=('___',"***"))

   Region Product___  Year___  Sales___ Product***  Year***  Sales***
0   North     Laptop     2024       150     Laptop     2024       150
1   North     Laptop     2024       150      Phone     2024        80
2   North      Phone     2024        80     Laptop     2024       150
3   North      Phone     2024        80      Phone     2024        80
4   South     Laptop     2024       120     Laptop     2024       120
5   South     Laptop     2024       120      Phone     2025       100
6   South      Phone     2025       100     Laptop     2024       120
7   South      Phone     2025       100      Phone     2025       100
8    East     Laptop     2025       170     Laptop     2025       170
9    East     Laptop     2025       170      Phone     2025        90
10   East      Phone     2025        90     Laptop     2025       170
11   East      Phone     2025        90      Phone     2025        90
12   West     Laptop     2024       140     Laptop     2024       140
13   West     Laptop     2024       140      Phone     2025       110
14   West      Phone     2025       110     Laptop     2024       140
15   West      Phone     2025       110      Phone     2025       110

In [62]:
import pandas as pd

# ==========================================================
# Problem 1: University Result Analysis
#
# Business Requirement:
#
# The Dean wants to compare the average marks of
# male and female students in every department.
#
# Bonus:
# Also display the highest marks.
# ==========================================================

df = pd.DataFrame({
    "Department":["CSE","CSE","ECE","ECE","EEE","EEE","CSE","ECE"],
    "Semester":[1,2,1,2,1,2,1,2],
    "Gender":["M","F","M","F","M","F","F","M"],
    "Marks":[82,91,75,88,79,94,95,84]
})

pt = pd.pivot_table(df,index='Department',columns="Gender",values='Marks',aggfunc=['mean','max'])
pt = pt.rename(columns={'mean':'Average marks','max': 'Highest Mark'})
pt

           Average marks       Highest Mark
Gender                 F     M            F   M
Department
CSE                 93.0  82.0           95  82
ECE                 88.0  79.5           88  84
EEE                 94.0  79.0           94  79

In [64]:
import pandas as pd

# ==========================================================
# Problem 2: Amazon Sales Dashboard
#
# Business Requirement:
#
# The Sales Director wants a report showing
# how much revenue each city generated
# from each product category.
#
# Also include an Overall total.
# ==========================================================

df = pd.DataFrame({
    "Category":["Electronics","Electronics","Furniture","Furniture",
                "Clothing","Clothing","Electronics","Furniture"],
    "City":["Chennai","Bangalore","Chennai","Mumbai",
            "Mumbai","Chennai","Mumbai","Bangalore"],
    "Revenue":[250000,300000,180000,220000,
               90000,120000,280000,240000]
})
pt= pd.pivot_table(df,index='City',columns='Category',values='Revenue',aggfunc='sum',margins=True,margins_name="Overall total",fill_value=0)
pt

Category       Clothing  Electronics  Furniture  Overall total
City
Bangalore             0       300000     240000         540000
Chennai          120000       250000     180000         550000
Mumbai            90000       280000     220000         590000
Overall total    210000       830000     640000        1680000

In [68]:
import pandas as pd

# ==========================================================
# Problem 3: Hospital Operations
#
# Business Requirement:
#
# Find the average number of patients handled
# by every doctor in each department.
#
# Missing combinations should display 0.
# ==========================================================

df = pd.DataFrame({
    "Doctor":["A","A","B","B","C","C","A","B"],
    "Department":["Cardiology","Neurology","Cardiology",
                  "Orthopedic","Neurology","Orthopedic",
                  "Orthopedic","Neurology"],
    "Patients":[12,8,15,11,14,13,10,16]
})

pt = pd.pivot_table(df,index="Department",columns='Doctor',values='Patients',aggfunc='mean',fill_value=0)
pt = pt.rename(columns={'A': "Average Patients Handled by A",'B': "Average Patients Handled by B",'C': "Average Patients Handled by C"})
pt

Doctor      Average Patients Handled by A  ...  Average Patients Handled by C
Department                                 ...
Cardiology                           12.0  ...                            0.0
Neurology                             8.0  ...                           14.0
Orthopedic                           10.0  ...                           13.0

[3 rows x 3 columns]

In [75]:
import pandas as pd

# ==========================================================
# Problem 4: Employee Salary Analytics
#
# Business Requirement:
#
# The HR team wants:
#
# 1. Average salary
# 2. Maximum salary
#
# for every department across every location.
#
# (Salary is in lakhs.)
# ==========================================================

df = pd.DataFrame({
    "Department":["IT","IT","IT","HR","HR",
                  "Finance","Finance","Marketing"],
    "Location":["Chennai","Bangalore","Chennai",
                "Mumbai","Mumbai","Delhi",
                "Delhi","Chennai"],
    "Salary":[7,8,9,5,6,10,11,7]
})
# index = Location
# columns = Department
# values = Salary
# aggfunc = ['mean','max']
# fill_value =
# margins =
# margins_name =
pt = pd.pivot_table(df,index='Location',columns='Department',values='Salary',aggfunc=['mean','max'],fill_value=0)
pt = pt.rename(columns={'mean':"Average Salary","max":'Highest Salary'})
pt

           Average Salary                     Highest Salary
Department        Finance   HR   IT Marketing        Finance HR IT Marketing
Location
Bangalore             0.0  0.0  8.0       0.0              0  0  8         0
Chennai               0.0  0.0  8.0       7.0              0  0  9         7
Delhi                10.5  0.0  0.0       0.0             11  0  0         0
Mumbai                0.0  5.5  0.0       0.0              0  6  0         0

In [78]:
import pandas as pd

# ==========================================================
# Problem 5: IPL Statistics
#
# Business Requirement:
#
# Create a report showing the total runs scored
# by each team in every season.
#
# Add grand totals.
# ==========================================================

df = pd.DataFrame({
    "Team":["CSK","CSK","RCB","RCB",
            "MI","MI","CSK","RCB"],
    "Season":[2023,2024,2023,2024,
              2023,2024,2023,2024],
    "Player":["Dhoni","Ruturaj","Kohli","Maxwell",
              "Rohit","Sky","Jadeja","Siraj"],
    "Runs":[180,620,650,420,500,540,350,80]
})

# index = Team
# columns = Season
# values = Runs
# aggfunc = sum
# fill_value = 0
# margins = True
# margins_name = grand totals
pt = pd.pivot_table(df,index='Team',columns='Season',values='Runs',aggfunc='sum',margins=True,margins_name='Grand total',fill_value=0)
pt = pt.rename(columns={2023:"Total run in 2023",2024:"Total run in 2024"})
pt

Season       Total run in 2023  Total run in 2024  Grand total
Team
CSK                        530                620         1150
MI                         500                540         1040
RCB                        650                500         1150
Grand total               1680               1660         3340

In [79]:
import pandas as pd

# ==========================================================
# Problem 6: Startup Funding
#
# Business Requirement:
#
# The VC firm wants to know:
#
# 1. Total funding
# 2. Average funding
#
# received from every investor each year.
# ==========================================================

df = pd.DataFrame({
    "Startup":["A","A","B","B","C","C","A","B"],
    "Year":[2022,2023,2022,2023,2022,2023,2024,2024],
    "Investor":["Sequoia","Accel","Accel","Tiger",
                "Tiger","Sequoia","Tiger","Accel"],
    "Funding":[20,35,18,40,15,28,50,42]
})

# index = Investor
# columns = Year
# values = Funding 
# aggfunc = sum
# fill_value = 0
# margins =
# margins_name =
pt = pd.pivot_table(df,index='Investor',columns='Year',values='Funding',aggfunc=['sum','mean'],fill_value=0)
pt=pt.rename(columns={'sum':" Total Funding",'mean':"Average Funding"})
pt

          Total Funding           Average Funding
Year               2022 2023 2024            2022  2023  2024
Investor
Accel                18   35   42            18.0  35.0  42.0
Sequoia              20   28    0            20.0  28.0   0.0
Tiger                15   40   50            15.0  40.0  50.0

In [80]:
import pandas as pd

# ==========================================================
# Problem 7: Netflix Analytics
#
# Business Requirement:
#
# Compare the average IMDb rating
# of every genre in each country.
#
# Also display the highest rating.
# ==========================================================

df = pd.DataFrame({
    "Genre":["Action","Drama","Comedy","Action",
             "Drama","Comedy","Action","Drama"],
    "Country":["India","India","USA","USA",
               "USA","India","UK","UK"],
    "Rating":[8.4,8.1,7.5,8.7,
              8.2,7.8,8.5,8.0]
})

# index = Country
# columns = Genre
# values = Rating
# aggfunc = [mean,max]
# fill_value = 0
# margins =
# margins_name =
pt = pd.pivot_table(df,index='Country',columns='Genre',values='Rating',aggfunc=['mean','max'],fill_value=0)
pt = pt.rename(columns={'mean': "Average Rating",'max':"Highest Rating"})
pt

        Average Rating              Highest Rating
Genre           Action Comedy Drama         Action Comedy Drama
Country
India              8.4    7.8   8.1            8.4    7.8   8.1
UK                 8.5    0.0   8.0            8.5    0.0   8.0
USA                8.7    7.5   8.2            8.7    7.5   8.2